"use strict";

module.exports = function bits({ img, I, JS }) {
  const v = (slug, title, layout, family, css, html, js = "") => ({ slug, title, layout, family, css, html, js });
  const atom = (category, slots, variants) => ({ category, role: "ornament", pageReady: false, slots, variants });

  return [
    atom("badges", ["visual"], [
      v("count-badge", "Count badge", "flex-row", "editorial", `.row{display:flex;gap:16px;padding:24px;align-items:center}.b{min-width:22px;height:22px;padding:0 6px;border-radius:99px;background:var(--ink);color:var(--on);display:inline-grid;place-items:center;font-size:.75rem}`, `<p class="row">Inbox <span class="b">3</span></p>`),
      v("status-badge", "Status badge", "flex-row", "studio", `.b{display:inline-flex;gap:6px;align-items:center;margin:20px;padding:6px 10px;border-radius:var(--r);border:1px solid var(--line)}i{width:8px;height:8px;border-radius:50%;background:#3d9a62;display:block}`, `<p class="b"><i></i> On site</p>`),
      v("soft-badge", "Soft badge", "flex-row", "soft", `.b{margin:20px;display:inline-block;background:var(--surface);border-radius:var(--r);padding:6px 10px}`, `<p class="b">Design phase</p>`),
      v("outline-badge", "Outline badge", "flex-row", "sharp", `.b{margin:20px;display:inline-block;border:1px solid var(--ink);padding:4px 8px;font-size:.8rem;letter-spacing:.08em;text-transform:uppercase}`, `<p class="b">New</p>`),
    ]),
    atom("tags", ["visual"], [
      v("filter-tags", "Filter tags", "flex-row", "editorial", `.row{display:flex;gap:8px;flex-wrap:wrap;padding:20px}button{min-height:40px;padding:0 12px;border-radius:var(--r);border:1px solid var(--line);background:var(--surface)}[aria-pressed=true]{background:var(--ink);color:var(--on)}`, `<div class="row" role="group" aria-label="Filters"><button type="button" aria-pressed="true">All</button><button type="button" aria-pressed="false">Homes</button><button type="button" aria-pressed="false">Shops</button></div>`),
      v("removable-tags", "Removable tags", "flex-row", "studio", `.t{display:inline-flex;align-items:center;gap:4px;margin:16px;border:1px solid var(--line);border-radius:var(--r);padding-left:10px}button{width:36px;height:36px;border:0;background:transparent;color:inherit}`, `<span class="t">Oak <button type="button" aria-label="Remove oak">${I.close}</button></span>`),
      v("outline-tags", "Outline tags", "flex-row", "soft", `.row{display:flex;gap:8px;padding:20px}span{border:1px solid var(--line);border-radius:var(--r);padding:6px 10px}`, `<p class="row"><span>Limewash</span><span>Oak</span><span>Brass</span></p>`),
      v("tag-group", "Tag group", "stack", "sharp", `.row{display:flex;gap:6px;padding:16px}span{background:var(--surface);border:1px solid var(--line);padding:4px 8px;font-size:.85rem}`, `<p class="row"><span>Active</span><span>June</span><span>Residential</span></p>`),
    ]),
    atom("avatars", ["media"], [
      v("circle-avatar", "Circle avatar", "flex-row", "editorial", `img{width:72px;height:72px;border-radius:50%;object-fit:cover;margin:20px}`, `${img(4, "Ada Loren")}`),
      v("avatar-group", "Avatar group", "flex-row", "studio", `.g{display:flex;padding:20px}img{width:48px;height:48px;border-radius:50%;object-fit:cover;margin-left:-8px;border:2px solid var(--bg)}.g img:first-child{margin-left:0}`, `<div class="g">${img(4, "Ada")}${img(5, "Miles")}${img(8, "Noor")}</div>`),
      v("name-avatar", "Avatar with name", "flex-row", "soft", `.row{display:flex;gap:10px;align-items:center;padding:16px}img{width:48px;height:48px;border-radius:50%;object-fit:cover}`, `<div class="row">${img(4, "Ada Loren")}<div><strong>Ada Loren</strong><p class="lede">Principal</p></div></div>`),
      v("status-avatar", "Avatar with status", "flex-row", "sharp", `.wrap{position:relative;width:64px;margin:20px}img{width:64px;height:64px;border-radius:50%;object-fit:cover}.dot{position:absolute;right:2px;bottom:2px;width:12px;height:12px;border-radius:50%;background:#2f7d4a;border:2px solid var(--bg)}`, `<div class="wrap">${img(5, "Miles Chen, available")}<span class="dot"></span></div><p style="padding:0 20px">Available</p>`),
    ]),
    atom("icons", ["visual"], [
      v("icon-set", "Icon set", "card-grid", "editorial", `.g{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;padding:16px;max-width:360px}span{display:grid;gap:4px;justify-items:center;font-size:.75rem;color:var(--muted);min-height:64px}`, `<div class="g"><span>${I.pin} Place</span><span>${I.phone} Call</span><span>${I.mail} Mail</span><span>${I.clock} Hours</span></div>`),
      v("icon-sizes", "Icon sizes", "flex-row", "studio", `.row{display:flex;gap:16px;align-items:center;padding:24px}`, `<div class="row">${I.search}${svgBigger()}</div>`),
      v("icon-buttons", "Icons in buttons", "flex-row", "soft", `.row{display:flex;gap:8px;padding:20px}`, `<div class="row"><button class="btn" type="button">${I.phone} Call</button><button class="btn gh" type="button" aria-label="Email">${I.mail}</button></div>`),
      v("feature-icons", "Feature icons", "card-grid", "sharp", `.g{display:grid;grid-template-columns:1fr 1fr;gap:12px;padding:16px;max-width:480px}article{display:flex;gap:8px}`, `<div class="g"><article>${I.check}<p>Written number first</p></article><article>${I.clock}<p>One crew on site</p></article></div>`),
    ]),
    atom("tables", ["visual"], [
      v("simple-table", "Simple table", "stack", "editorial", `table{width:min(680px,calc(100% - 32px));margin:16px;border-collapse:collapse}th,td{text-align:left;padding:10px 8px;border-bottom:1px solid var(--line)}`, `<table><thead><tr><th scope="col">Room</th><th scope="col">Status</th></tr></thead><tbody><tr><th scope="row">Kitchen</th><td>Drawing</td></tr><tr><th scope="row">Stair</th><td>On site</td></tr></tbody></table>`),
      v("striped-table", "Striped table", "stack", "studio", `table{width:min(680px,calc(100% - 32px));margin:16px;border-collapse:collapse}th,td{text-align:left;padding:10px}tbody tr:nth-child(odd){background:var(--surface)}`, `<table><caption class="ey" style="text-align:left">Hours</caption><tbody><tr><th scope="row">Tue–Fri</th><td>9–5</td></tr><tr><th scope="row">Sat</th><td>10–2</td></tr></tbody></table>`),
      v("compact-table", "Compact table", "stack", "soft", `table{width:min(560px,calc(100% - 24px));margin:12px;border-collapse:collapse;font-size:.92rem}td,th{padding:6px 8px;text-align:left;border-bottom:1px solid var(--line)}`, `<table><thead><tr><th>Item</th><th>Qty</th></tr></thead><tbody><tr><td>Hinge</td><td>12</td></tr><tr><td>Pull</td><td>8</td></tr></tbody></table>`),
      v("responsive-table", "Responsive cards table", "stack", "sharp", `.cards{display:grid;gap:8px;padding:12px}@media(min-width:800px){.cards{display:none}}table{display:none;width:calc(100% - 24px);margin:12px;border-collapse:collapse}@media(min-width:800px){table{display:table}}td,th{text-align:left;padding:8px;border-bottom:1px solid var(--line)}.c{border:1px solid var(--line);padding:10px}`, `<div class="cards"><article class="c"><strong>Kitchen</strong><p>Drawing</p></article></div><table><thead><tr><th>Room</th><th>Status</th></tr></thead><tbody><tr><td>Kitchen</td><td>Drawing</td></tr></tbody></table>`),
    ]),
    atom("lists", ["visual"], [
      v("definition-list", "Definition list", "stack", "editorial", `dl{max-width:480px;padding:12px 20px}div{display:grid;grid-template-columns:120px 1fr;gap:8px;padding:8px 0;border-bottom:1px solid var(--line)}@media(max-width:800px){div{grid-template-columns:1fr}}`, `<dl><div><dt>Lead</dt><dd>Ada Loren</dd></div><div><dt>Phase</dt><dd>Drawings</dd></div></dl>`),
      v("media-list", "Media list", "stack", "studio", `article{display:grid;grid-template-columns:96px 1fr;gap:12px;padding:12px 16px;align-items:center}img{width:96px;height:72px;object-fit:cover}`, `<article>${img(0, "Living room")}<div><h3>Hill house</h3><p class="lede">Living and stair</p></div></article>`),
      v("numbered-list", "Numbered list", "numbered-list", "soft", `ol{max-width:460px;padding:8px 20px 8px 40px}li{margin:8px 0}`, `<ol><li>Walk the site</li><li>Write the number</li><li>Draw the room</li></ol>`),
      v("check-list", "Checklist", "stack", "sharp", `li{list-style:none;display:flex;gap:8px;align-items:center;min-height:36px}ul{padding:12px 20px;margin:0}`, `<ul><li>${I.check} Brief written</li><li>${I.check} Budget sent</li><li>Samples out</li></ul>`),
    ]),
    atom("pagination", ["cta"], [
      v("number-pages", "Numbered pages", "flex-row", "editorial", `nav{display:flex;gap:6px;padding:20px}a,span{min-width:44px;height:44px;display:grid;place-items:center;border:1px solid var(--line);border-radius:10px}[aria-current]{background:var(--ink);color:var(--on)}`, `<nav aria-label="Pages"><a href="#p">Prev</a><a href="#1" aria-current="page">1</a><a href="#2">2</a><a href="#3">3</a><a href="#n">Next</a></nav>`),
      v("simple-pages", "Previous and next", "flex-row", "studio", `nav{display:flex;justify-content:space-between;padding:16px;max-width:480px}`, `<nav aria-label="Pages"><a class="btn gh" href="#p">Previous</a><a class="btn gh" href="#n">Next</a></nav>`),
      v("compact-pages", "Compact pages", "centered", "soft", `p{padding:16px;color:var(--muted)}`, `<p>Page 2 of 6 · <a href="#n">Next</a></p>`),
      v("load-more", "Load more", "centered", "sharp", `.c{padding:20px;text-align:center}`, `<div class="c"><button class="btn gh" type="button">Load more</button></div>`),
    ]),
    atom("breadcrumbs", ["nav-links"], [
      v("slash-crumbs", "Slash breadcrumbs", "flex-row", "editorial", `nav{padding:16px 20px}ol{display:flex;gap:8px;list-style:none;padding:0;margin:0;flex-wrap:wrap}li:not(:last-child)::after{content:" /";color:var(--muted);margin-left:8px}`, `<nav aria-label="Breadcrumb"><ol><li><a href="#w">Work</a></li><li><a href="#h">Homes</a></li><li aria-current="page">Hill house</li></ol></nav>`),
      v("chevron-crumbs", "Chevron breadcrumbs", "flex-row", "studio", `ol{display:flex;gap:6px;list-style:none;padding:16px;margin:0;align-items:center;flex-wrap:wrap}`, `<nav aria-label="Breadcrumb"><ol><li><a href="#s">Studio</a></li><li aria-hidden="true">${I.chev}</li><li aria-current="page">Journal</li></ol></nav>`),
      v("home-crumbs", "Home breadcrumbs", "flex-row", "soft", `nav{padding:16px}a{min-height:44px;display:inline-flex;align-items:center}`, `<nav aria-label="Breadcrumb"><a href="#h">${I.pin} Home</a> <span aria-hidden="true">/</span> <span aria-current="page">Visit</span></nav>`),
      v("condensed-crumbs", "Condensed breadcrumbs", "stack", "sharp", `nav{padding:12px 16px;font-size:.92rem}`, `<nav aria-label="Breadcrumb">Work / <a href="#homes">Homes</a> / <span aria-current="page">Hill house</span></nav>`),
    ]),
    atom("progress", ["visual"], [
      v("bar-progress", "Progress bar", "stack", "editorial", `.box{max-width:420px;padding:20px}.track{height:8px;background:var(--line);border-radius:99px;overflow:hidden}.fill{width:60%;height:100%;background:var(--accent)}`, `<div class="box"><p>Drawings <span>60%</span></p><div class="track" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" aria-label="Drawings"><div class="fill"></div></div></div>`),
      v("step-progress", "Step progress", "flex-row", "studio", `ol{display:flex;gap:12px;list-style:none;padding:16px;margin:0}li{min-height:44px;display:flex;align-items:center}[aria-current]{font-weight:750}`, `<ol><li>Brief</li><li aria-current="step">Draw</li><li>Build</li></ol>`),
      v("ring-progress", "Ring progress", "centered", "soft", `.r{width:88px;height:88px;border-radius:50%;margin:20px;display:grid;place-items:center;background:conic-gradient(var(--accent) 70%, var(--line) 0)}span{width:64px;height:64px;border-radius:50%;background:var(--bg);display:grid;place-items:center}`, `<div class="r" role="img" aria-label="70 percent complete"><span>70%</span></div>`),
      v("labeled-progress", "Labeled progress", "stack", "sharp", `.row{display:flex;justify-content:space-between;max-width:420px;padding:8px 16px;border-bottom:1px solid var(--line)}`, `<div><div class="row"><span>Survey</span><strong>Done</strong></div><div class="row"><span>Drawings</span><strong>In review</strong></div><div class="row"><span>Install</span><strong>Waiting</strong></div></div>`),
    ]),
    atom("loaders", ["visual"], [
      v("spinner-loader", "Spinner", "centered", "editorial", `.s{width:36px;height:36px;margin:28px;border:2px solid var(--line);border-top-color:var(--ink);border-radius:50%;animation:spin 1s linear infinite}@keyframes spin{to{transform:rotate(360deg)}}`, `<div class="s" role="status" aria-label="Loading"></div>`),
      v("bar-loader", "Loading bar", "band", "studio", `.track{height:4px;background:var(--line)}.fill{width:40%;height:100%;background:var(--accent)}`, `<div class="track" role="progressbar" aria-label="Loading" aria-valuetext="Loading"><div class="fill"></div></div>`),
      v("dots-loader", "Loading dots", "flex-row", "soft", `.row{display:flex;gap:6px;padding:28px}i{width:8px;height:8px;border-radius:50%;background:var(--ink);display:block}`, `<p class="row" role="status" aria-label="Loading"><i></i><i></i><i></i> Loading</p>`),
      v("text-loader", "Loading text", "stack", "sharp", `p{padding:24px}`, `<p role="status">Loading the drawing set…</p>`),
    ]),
    atom("dividers", ["visual"], [
      v("line-divider", "Line divider", "band", "editorial", `hr{border:0;border-top:1px solid var(--line);margin:24px}`, `<hr>`),
      v("labeled-divider", "Labeled divider", "centered", "studio", `.d{display:grid;grid-template-columns:1fr auto 1fr;gap:12px;align-items:center;padding:16px 20px;color:var(--muted)}.d::before,.d::after{content:"";height:1px;background:var(--line)}`, `<p class="d">Or write instead</p>`),
      v("space-divider", "Space divider", "stack", "soft", `.sp{height:48px}`, `<div class="sp" role="separator" aria-hidden="true"></div>`),
      v("ornament-divider", "Short rule", "centered", "sharp", `.r{width:48px;height:1px;background:var(--ink);margin:24px}`, `<div class="r" role="separator"></div>`),
    ]),
    atom("skeletons", ["visual"], [
      v("card-skeleton", "Card skeleton", "card-grid", "editorial", `.s{background:linear-gradient(90deg,var(--line),transparent,var(--line));background-size:200% 100%;animation:sh 1.2s infinite;border-radius:8px}@keyframes sh{to{background-position:-200% 0}}.card{width:240px;margin:16px}.m{height:140px}.l{height:14px;margin-top:10px}`, `<article class="card" aria-hidden="true"><div class="s m"></div><div class="s l"></div><div class="s l" style="width:60%"></div></article>`),
      v("list-skeleton", "List skeleton", "stack", "studio", `.row{display:grid;grid-template-columns:48px 1fr;gap:10px;padding:12px 16px;max-width:420px}.s{background:var(--line);border-radius:8px}.a{width:48px;height:48px;border-radius:50%}.b{height:12px;margin-top:8px}`, `<div aria-hidden="true"><div class="row"><div class="s a"></div><div><div class="s b"></div><div class="s b" style="width:70%"></div></div></div></div>`),
      v("article-skeleton", "Article skeleton", "stack", "soft", `.s{height:12px;background:var(--line);border-radius:6px;margin:8px 16px;max-width:460px}.t{height:28px;width:70%}`, `<div aria-hidden="true"><div class="s t"></div><div class="s"></div><div class="s"></div><div class="s" style="width:80%"></div></div>`),
      v("table-skeleton", "Table skeleton", "stack", "sharp", `.s{height:16px;background:var(--line);margin:10px 16px}`, `<div aria-hidden="true"><div class="s"></div><div class="s"></div><div class="s" style="width:66%"></div></div>`),
    ]),
    atom("empty-states", ["headline", "cta"], [
      v("no-results", "No results", "centered", "editorial", `.c{text-align:center;padding:48px 20px}`, `<div class="c">${I.search}<h2>No matches</h2><p class="lede">Try a material or a room.</p></div>`),
      v("no-data", "Nothing here yet", "centered", "studio", `.c{padding:40px 20px;max-width:420px}`, `<div class="c"><h2>No projects yet</h2><p class="lede">The first one starts with a visit.</p><a class="btn" href="#visit" style="margin-top:12px">Book</a></div>`),
      v("first-run", "First run", "centered", "soft", `.c{padding:36px 20px}`, `<div class="c"><h2>Add a sample</h2><p class="lede">Photograph a finish and pin it here.</p><button class="btn" type="button" style="margin-top:10px">Add photo</button></div>`),
      v("error-empty", "Could not load", "centered", "sharp", `.c{padding:36px 20px}`, `<div class="c" role="alert"><h2>Could not load files</h2><p class="lede">Check the connection and retry.</p><button class="btn gh" type="button" style="margin-top:10px">Retry</button></div>`),
    ]),
    atom("errors", ["headline", "cta"], [
      v("error-404", "Missing page", "centered", "editorial", `.c{min-height:100vh;display:grid;place-items:center;text-align:center;padding:24px}h1{font-size:clamp(3rem,8vw,6rem)}`, `<main class="c"><p class="ey">404</p><h1>That page is gone.</h1><p class="lede">The link may have moved.</p><a class="btn" href="#top" style="margin-top:16px">Back home</a></main>`),
      v("error-500", "Server error", "centered", "studio", `.c{min-height:80vh;display:grid;align-content:center;padding:32px;max-width:520px}`, `<main class="c"><h1>Something failed.</h1><p class="lede">The note did not send. Try again in a minute.</p><button class="btn" type="button" style="margin-top:12px">Retry</button></main>`),
      v("error-offline", "Offline", "centered", "soft", `.c{padding:48px 20px;text-align:center}`, `<main class="c"><h1>You are offline.</h1><p class="lede">Open notes are still on this device.</p></main>`),
      v("error-forbidden", "Forbidden", "centered", "sharp", `.c{padding:48px 20px}`, `<main class="c"><h1>No access</h1><p class="lede">Ask the project lead for an invite.</p><a class="btn gh" href="#top">Home</a></main>`),
    ]),
    atom("status", ["visual"], [
      v("dot-status", "Dot status", "flex-row", "editorial", `.row{display:flex;gap:8px;align-items:center;padding:16px}i{width:8px;height:8px;border-radius:50%;background:#2f7d4a}`, `<p class="row"><i></i> Live on site</p>`),
      v("pill-status", "Pill status", "flex-row", "studio", `.p{display:inline-flex;margin:16px;padding:6px 10px;border-radius:var(--r);background:var(--surface);border:1px solid var(--line)}`, `<p class="p">In review</p>`),
      v("text-status", "Text status", "stack", "soft", `.row{display:flex;justify-content:space-between;max-width:360px;padding:10px 16px;border-bottom:1px solid var(--line)}`, `<div><div class="row"><span>Drawings</span><span>In review</span></div><div class="row"><span>Samples</span><span>Shipped</span></div></div>`),
      v("pulse-status", "Busy status", "flex-row", "sharp", `.row{display:flex;gap:8px;align-items:center;padding:16px}i{width:8px;height:8px;border-radius:50%;background:var(--ink)}`, `<p class="row" role="status"><i></i> Syncing files</p>`),
    ]),
    atom("code", ["visual"], [
      v("code-block", "Code block", "stack", "editorial", `pre{margin:16px;padding:14px;background:var(--ink);color:var(--on);border-radius:var(--r);overflow:auto;max-width:560px}code{font-family:ui-monospace,monospace;font-size:.9rem}`, `<pre><code>room: kitchen\nlight: west\nfinish: limewash</code></pre>`),
      v("inline-code", "Inline code", "stack", "studio", `p{padding:16px;max-width:460px}code{font-family:ui-monospace,monospace;background:var(--surface);padding:2px 6px;border-radius:6px}`, `<p>Set the phase to <code>drawing</code> before you share the link.</p>`),
      v("file-code", "Code with filename", "stack", "soft", `.f{max-width:520px;margin:16px;border:1px solid var(--line);border-radius:var(--r);overflow:hidden}.h{padding:8px 12px;border-bottom:1px solid var(--line);background:var(--surface)}pre{margin:0;padding:12px;overflow:auto}`, `<div class="f"><div class="h">notes.txt</div><pre><code>Keep the west window clear.</code></pre></div>`),
      v("copy-code", "Code with copy", "stack", "sharp", `.f{max-width:520px;margin:16px;border:1px solid var(--line)}header{display:flex;justify-content:space-between;align-items:center;padding:6px 10px;border-bottom:1px solid var(--line)}pre{margin:0;padding:12px;overflow:auto}button{min-height:36px}`, `<div class="f"><header><span>spec.json</span><button class="btn gh" type="button" data-copy>Copy</button></header><pre><code>{"phase":"draw"}</code></pre></div>`, JS.copy),
    ]),
    atom("charts", ["visual"], [
      v("bar-chart", "Bar chart", "card-grid", "editorial", `.chart{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;align-items:end;height:180px;max-width:420px;padding:16px}.bar{background:var(--ink);border-radius:6px 6px 0 0}span{display:block;text-align:center;font-size:.8rem;color:var(--muted)}`, `<figure role="img" aria-label="Bookings. Spring 18, Summer 30, Autumn 24, Winter 14."><div class="chart"><div><div class="bar" style="height:50%"></div><span>18</span></div><div><div class="bar" style="height:90%"></div><span>30</span></div><div><div class="bar" style="height:70%"></div><span>24</span></div><div><div class="bar" style="height:40%"></div><span>14</span></div></div></figure>`),
      v("line-chart", "Trend list", "stack", "studio", `.row{display:flex;justify-content:space-between;max-width:360px;padding:8px 16px;border-bottom:1px solid var(--line)}`, `<figure><figcaption class="ey" style="padding:12px 16px 0">Visits</figcaption><div class="row"><span>Jan</span><strong>12</strong></div><div class="row"><span>Feb</span><strong>18</strong></div><div class="row"><span>Mar</span><strong>15</strong></div></figure>`),
      v("donut-chart", "Donut chart", "flex-row", "soft", `.row{display:flex;gap:16px;align-items:center;padding:16px}.d{width:96px;height:96px;border-radius:50%;background:conic-gradient(#6e3824 0 55%, #1b1814 55% 80%, #d8d2c8 80%);display:grid;place-items:center}i{width:58px;height:58px;border-radius:50%;background:var(--bg);display:block}`, `<figure class="row" aria-label="Work mix. Homes 55 percent, shops 25 percent, other 20 percent."><div class="d" aria-hidden="true"><i></i></div><ul><li>Homes 55%</li><li>Shops 25%</li><li>Other 20%</li></ul></figure>`),
      v("stat-chart", "Single stat", "centered", "sharp", `.n{font-family:var(--d);font-size:3rem;padding:12px 16px 0}`, `<figure><p class="n">18</p><figcaption class="lede" style="padding:0 16px 16px">visits this month</figcaption></figure>`),
    ]),
    atom("audio", ["media"], [
      v("audio-bar", "Audio player", "stack", "editorial", `figure{max-width:440px;margin:16px;padding:12px;background:var(--surface);border-radius:var(--r)}audio{width:100%;margin-top:8px}`, `<figure><figcaption>Site walk, Thursday</figcaption><audio controls preload="none" src="https://interactive-examples.mdn.mozilla.net/media/cc0-audio/t-rex-roar.mp3"></audio></figure>`),
      v("audio-card", "Audio card", "card-grid", "studio", `article{max-width:360px;margin:16px;padding:14px;border:1px solid var(--line);border-radius:var(--r)}audio{width:100%;margin-top:8px}`, `<article><h3>Finish notes</h3><p class="lede">3 min</p><audio controls preload="none" src="https://interactive-examples.mdn.mozilla.net/media/cc0-audio/t-rex-roar.mp3"></audio></article>`),
      v("audio-minimal", "Minimal audio", "stack", "soft", `audio{width:min(420px,calc(100% - 32px));margin:20px}`, `<audio controls preload="none" aria-label="Studio note" src="https://interactive-examples.mdn.mozilla.net/media/cc0-audio/t-rex-roar.mp3"></audio>`),
      v("playlist", "Playlist", "stack", "sharp", `li{list-style:none;display:flex;justify-content:space-between;padding:10px 16px;border-bottom:1px solid var(--line);max-width:420px}ul{margin:0;padding:0}`, `<ul><li><span>Stair walk</span><span>2:10</span></li><li><span>Client call</span><span>8:04</span></li></ul>`),
    ]),
    atom("authentication", ["form-fields", "cta"], [
      v("login-form", "Login", "form-stack", "editorial", `form{max-width:380px;margin:24px;display:grid;gap:12px;padding:20px;background:var(--surface);border-radius:var(--r)}`, `<form><h2>Sign in</h2><label class="fld">Email<input type="email" autocomplete="username" required></label><label class="fld">Password<input type="password" autocomplete="current-password" required></label><button class="btn" type="submit">Sign in</button></form>`),
      v("signup-form", "Create account", "form-stack", "studio", `form{max-width:400px;margin:20px;display:grid;gap:10px}`, `<form><h2>Create account</h2><label class="fld">Name<input autocomplete="name" required></label><label class="fld">Email<input type="email" autocomplete="email" required></label><label class="fld">Password<input type="password" autocomplete="new-password" required></label><button class="btn" type="submit">Create</button></form>`),
      v("split-auth", "Split sign in", "split-media", "soft", `.g{display:grid;grid-template-columns:1fr 1fr;min-height:100vh}.copy{padding:32px;display:grid;align-content:center;gap:10px}@media(max-width:800px){.g{grid-template-columns:1fr}}`, `<section class="g">${img(7, "Studio table")}<form class="copy"><h2>Welcome back</h2><label class="fld">Email<input type="email" required></label><button class="btn" type="submit">Continue</button></form></section>`),
      v("magic-link", "Magic link", "form-stack", "sharp", `form{max-width:400px;margin:24px;display:grid;gap:10px}`, `<form><h2>Email a link</h2><p class="lede">No password. The link expires in 20 minutes.</p><label class="fld">Email<input type="email" required autocomplete="email"></label><button class="btn" type="submit">Send link</button></form>`),
    ]),
    atom("profiles", ["media", "form-fields"], [
      v("profile-header", "Profile header", "flex-row", "editorial", `.row{display:flex;gap:14px;align-items:center;padding:20px}img{width:72px;height:72px;border-radius:50%;object-fit:cover}`, `<header class="row">${img(4, "Ada Loren")}<div><h2>Ada Loren</h2><p class="lede">Principal · Harbor Ave</p></div></header>`),
      v("profile-stats", "Profile stats", "card-grid", "studio", `.g{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;max-width:480px;padding:12px 16px}div{background:var(--surface);padding:12px;border-radius:var(--r)}`, `<section><div class="g"><div><strong>12</strong><p class="lede">Projects</p></div><div><strong>4</strong><p class="lede">Active</p></div><div><strong>8</strong><p class="lede">Years</p></div></div></section>`),
      v("edit-profile", "Edit profile", "form-stack", "soft", `form{max-width:440px;margin:16px;display:grid;gap:10px}`, `<form><h2>Edit profile</h2><label class="fld">Name<input value="Ada Loren"></label><label class="fld">Role<input value="Principal"></label><button class="btn" type="button">Save</button></form>`),
      v("cover-profile", "Cover profile", "stack", "sharp", `.cover{height:120px;background:var(--ink)}.row{display:flex;gap:12px;align-items:end;padding:0 16px 16px;margin-top:-28px}img{width:72px;height:72px;object-fit:cover;border:3px solid var(--bg)}`, `<header><div class="cover"></div><div class="row">${img(4, "Ada Loren")}<h2>Ada Loren</h2></div></header>`),
    ]),
    atom("dashboards", ["visual"], [
      v("kpi-dashboard", "KPI dashboard", "card-grid", "editorial", `.g{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;padding:16px}.c{background:var(--surface);padding:14px;border-radius:var(--r);border:1px solid var(--line)}@media(max-width:800px){.g{grid-template-columns:1fr}}`, `<section class="g"><article class="c"><p class="ey">Open</p><h2>6</h2></article><article class="c"><p class="ey">This week</p><h2>2</h2></article><article class="c"><p class="ey">Waiting</p><h2>1</h2></article></section>`),
      v("activity-dashboard", "Activity dashboard", "stack", "studio", `li{list-style:none;padding:12px 16px;border-bottom:1px solid var(--line)}ul{margin:0;padding:0}`, `<section><h2 style="padding:16px">Today</h2><ul><li>Samples delivered to Hill house</li><li>Drawing shared with the client</li></ul></section>`),
      v("simple-dashboard", "Simple dashboard", "split-media", "soft", `.g{display:grid;grid-template-columns:220px 1fr;min-height:100vh}@media(max-width:800px){.g{grid-template-columns:1fr}aside{border-bottom:1px solid var(--line)}}aside{border-right:1px solid var(--line);padding:12px}main{padding:16px}a{display:flex;min-height:40px;align-items:center}`, `<div class="g"><aside><a href="#b" aria-current="page">Board</a><a href="#p">Projects</a></aside><main><h2>Board</h2><p class="lede">Two visits tomorrow.</p></main></div>`),
      v("split-dashboard", "Split metrics", "multi-column", "sharp", `.g{display:grid;grid-template-columns:1.2fr .8fr;gap:12px;padding:16px}@media(max-width:800px){.g{grid-template-columns:1fr}}.c{border:1px solid var(--line);padding:12px}`, `<section class="g"><article class="c"><h2>Schedule</h2><p>Thu 10:00 Hill house</p></article><article class="c"><h2>Inbox</h2><p>3 unread</p></article></section>`),
    ]),
    atom("settings", ["form-fields"], [
      v("toggle-settings", "Toggle settings", "stack", "editorial", `.row{display:flex;justify-content:space-between;gap:12px;align-items:center;max-width:480px;padding:12px 16px;border-bottom:1px solid var(--line)}`, `<form><h2 style="padding:16px">Notifications</h2><label class="row">Email notes <input type="checkbox" role="switch" checked></label><label class="row">Texts from the crew <input type="checkbox" role="switch"></label></form>`),
      v("section-settings", "Sectioned settings", "stack", "studio", `section{max-width:520px;padding:8px 16px 16px;border-bottom:1px solid var(--line)}`, `<form><section><h2>Studio</h2><label class="fld">Name<input value="Northline"></label></section><section><h2>Address</h2><label class="fld">Street<input value="18 Harbor Ave"></label></section><button class="btn" type="button" style="margin:12px 16px">Save</button></form>`),
      v("account-settings", "Account settings", "form-stack", "soft", `form{max-width:420px;margin:16px;display:grid;gap:10px}`, `<form><h2>Account</h2><label class="fld">Email<input type="email" value="ada@northline.example"></label><button class="btn gh" type="button">Change password</button></form>`),
      v("preference-settings", "Preferences", "stack", "sharp", `label{display:flex;gap:8px;align-items:center;min-height:44px}`, `<fieldset style="border:0;padding:12px 16px"><legend>Density</legend><label><input type="radio" name="d" checked> Comfortable</label><label><input type="radio" name="d"> Compact</label></fieldset>`),
    ]),
    atom("steppers", ["cta"], [
      v("horizontal-steps", "Horizontal steps", "flex-row", "editorial", `ol{display:flex;gap:16px;list-style:none;padding:16px;margin:0;flex-wrap:wrap}[aria-current]{font-weight:750;border-bottom:2px solid var(--ink)}`, `<ol><li>Brief</li><li aria-current="step">Design</li><li>Build</li></ol>`),
      v("vertical-steps", "Vertical steps", "stack", "studio", `li{list-style:none;padding:8px 0 8px 12px;border-left:2px solid var(--line)}ol{margin:0;padding:12px 16px}[aria-current]{border-color:var(--ink);font-weight:700}`, `<ol><li>Visit booked</li><li aria-current="step">Notes due</li><li>Proposal</li></ol>`),
      v("numbered-steps", "Numbered steps", "flex-row", "soft", `.n{width:28px;height:28px;border-radius:50%;display:inline-grid;place-items:center;background:var(--ink);color:var(--on);margin-right:6px}ol{display:flex;gap:18px;list-style:none;padding:16px;flex-wrap:wrap}`, `<ol><li><span class="n">1</span>Scope</li><li><span class="n">2</span>Fee</li><li><span class="n">3</span>Start</li></ol>`),
      v("wizard-card", "Wizard card", "form-stack", "sharp", `.card{max-width:440px;margin:16px;padding:16px;border:1px solid var(--line);background:var(--surface)}`, `<form class="card"><p class="ey">Step 2 of 3</p><h2>The room</h2><label class="fld">Which room?<input value="Kitchen"></label><div style="display:flex;gap:8px;margin-top:12px"><button class="btn gh" type="button">Back</button><button class="btn" type="button">Next</button></div></form>`),
    ]),
    atom("data-grids", ["visual"], [
      v("basic-grid", "Data grid", "stack", "editorial", `table{width:calc(100% - 24px);margin:12px;border-collapse:collapse}th,td{text-align:left;padding:8px;border-bottom:1px solid var(--line)}thead th{position:sticky;top:0;background:var(--bg)}`, `<div style="overflow:auto;max-height:280px"><table><thead><tr><th>Project</th><th>Phase</th><th>Lead</th></tr></thead><tbody><tr><td>Hill house</td><td>Draw</td><td>Ada</td></tr><tr><td>Market</td><td>Build</td><td>Miles</td></tr></tbody></table></div>`),
      v("select-grid", "Selectable grid", "stack", "studio", `td,th{padding:8px;border-bottom:1px solid var(--line);text-align:left}table{width:calc(100% - 16px);margin:8px;border-collapse:collapse}`, `<table><thead><tr><th scope="col"><span class="sr">Select</span></th><th>Name</th></tr></thead><tbody><tr><td><input type="checkbox" aria-label="Select Hill house"></td><td>Hill house</td></tr></tbody></table>`),
      v("dense-grid", "Dense grid", "stack", "soft", `table{width:100%;border-collapse:collapse;font-size:.9rem}td,th{padding:4px 8px;border-bottom:1px solid var(--line);text-align:left}`, `<table><tbody><tr><th scope="row">SKU-14</th><td>Hinge</td><td>12</td></tr><tr><th scope="row">SKU-22</th><td>Pull</td><td>8</td></tr></tbody></table>`),
      v("responsive-grid", "Stacked records", "stack", "sharp", `article{border:1px solid var(--line);margin:8px 12px;padding:10px}`, `<div><article><strong>Hill house</strong><p class="lede">Draw · Ada</p></article><article><strong>Market</strong><p class="lede">Build · Miles</p></article></div>`),
    ]),
    atom("filters", ["form-fields"], [
      v("chip-filters", "Chip filters", "flex-row", "editorial", `.row{display:flex;gap:8px;flex-wrap:wrap;padding:16px}button{min-height:40px;border-radius:var(--r);border:1px solid var(--line);background:transparent;padding:0 12px}[aria-pressed=true]{background:var(--ink);color:var(--on)}`, `<div class="row"><button type="button" aria-pressed="true">All</button><button type="button" aria-pressed="false">Active</button><button type="button" aria-pressed="false">Archive</button></div>`),
      v("sidebar-filters", "Sidebar filters", "stack", "studio", `aside{width:220px;min-height:100vh;padding:12px;border-right:1px solid var(--line)}label{display:flex;gap:8px;min-height:36px;align-items:center}`, `<aside aria-label="Filters"><p class="ey">Phase</p><label><input type="checkbox" checked> Draw</label><label><input type="checkbox"> Build</label></aside>`),
      v("bar-filters", "Filter bar", "flex-row", "soft", `.bar{display:flex;gap:8px;padding:12px;flex-wrap:wrap;align-items:center}select,input{min-height:44px}`, `<div class="bar"><label>Phase <select><option>Any</option><option>Draw</option></select></label><label>Lead <input placeholder="Name"></label></div>`),
      v("applied-filters", "Applied filters", "flex-row", "sharp", `.row{display:flex;gap:8px;align-items:center;padding:12px;flex-wrap:wrap}.t{border:1px solid var(--line);padding:4px 8px}`, `<p class="row">Filtered by <span class="t">June</span><button class="btn gh" type="button">Clear</button></p>`),
    ]),
    atom("ratings", ["visual"], [
      v("star-rating", "Star rating display", "flex-row", "editorial", `.row{display:flex;gap:4px;padding:16px;color:var(--ink)}`, `<p class="row" role="img" aria-label="4 of 5">${I.star}${I.star}${I.star}${I.star}<span style="opacity:.35">${I.star}</span></p>`),
      v("score-rating", "Score", "stack", "studio", `.n{font-family:var(--d);font-size:2.4rem;padding:8px 16px 0}`, `<figure><p class="n">4.8</p><figcaption class="lede" style="padding:0 16px 12px">Average of 32 notes</figcaption></figure>`),
      v("distribution", "Rating distribution", "stack", "soft", `.row{display:grid;grid-template-columns:24px 1fr 32px;gap:8px;align-items:center;max-width:320px;margin:6px 16px}.bar{height:8px;background:var(--line)}i{display:block;height:100%;background:var(--ink)}`, `<div><div class="row"><span>5</span><span class="bar"><i style="width:70%"></i></span><span>22</span></div><div class="row"><span>4</span><span class="bar"><i style="width:20%"></i></span><span>7</span></div></div>`),
      v("input-rating", "Rating input", "flex-row", "sharp", `.row{display:flex;padding:12px;gap:6px}button{min-width:44px;height:44px;border:1px solid var(--line);background:transparent;color:inherit}[aria-pressed=true]{background:var(--ink);color:var(--on)}`, `<div class="row" role="radiogroup" aria-label="Rate the visit"><button type="button" aria-pressed="true" aria-label="1 of 5">1</button><button type="button" aria-pressed="true" aria-label="2 of 5">2</button><button type="button" aria-pressed="false" aria-label="3 of 5">3</button><button type="button" aria-pressed="false" aria-label="4 of 5">4</button><button type="button" aria-pressed="false" aria-label="5 of 5">5</button></div>`),
    ]),
    atom("timeline", ["visual"], [
      v("vertical-timeline", "Vertical timeline", "stack", "editorial", `li{list-style:none;border-left:2px solid var(--line);padding:0 0 16px 14px;margin-left:8px}ol{margin:16px;padding:0}`, `<ol><li><strong>March 2</strong><p class="lede">Visit booked</p></li><li><strong>March 9</strong><p class="lede">Notes sent</p></li></ol>`),
      v("alternating-timeline", "Two-column timeline", "multi-column", "studio", `.g{display:grid;grid-template-columns:1fr 1fr;gap:12px;padding:16px}@media(max-width:800px){.g{grid-template-columns:1fr}}`, `<div class="g"><article><p class="ey">Week 1</p><p>Survey</p></article><article><p class="ey">Week 3</p><p>Drawings</p></article></div>`),
      v("compact-timeline", "Compact timeline", "stack", "soft", `.row{display:flex;gap:12px;padding:8px 16px}.d{width:72px;color:var(--muted)}`, `<div><div class="row"><span class="d">Mon</span><span>Site</span></div><div class="row"><span class="d">Thu</span><span>Review</span></div></div>`),
      v("milestone-timeline", "Milestones", "flex-row", "sharp", `ol{display:flex;gap:18px;list-style:none;padding:16px;margin:0;flex-wrap:wrap}li{min-width:100px}`, `<ol><li><strong>01</strong><p>Brief</p></li><li><strong>02</strong><p>Fee</p></li><li><strong>03</strong><p>Build</p></li></ol>`),
    ]),
    atom("newsletter", ["form-fields", "cta"], [
      v("inline-newsletter", "Inline note signup", "flex-row", "editorial", `form{display:flex;gap:8px;flex-wrap:wrap;padding:16px;max-width:520px}input{flex:1;min-width:200px}`, `<form><label class="fld" style="flex:1">Email<input type="email" required placeholder="you@studio.com"></label><button class="btn" type="submit">Join</button></form>`),
      v("card-newsletter", "Card signup", "form-stack", "studio", `.card{max-width:400px;margin:16px;padding:16px;background:var(--surface);border-radius:var(--r);display:grid;gap:10px}`, `<form class="card"><h2>Field notes</h2><p class="lede">A short letter, once a month.</p><label class="fld">Email<input type="email" required></label><button class="btn" type="submit">Subscribe</button></form>`),
      v("band-newsletter", "Band signup", "band", "soft", `.band{display:flex;justify-content:space-between;gap:12px;flex-wrap:wrap;align-items:end;padding:20px;background:var(--surface)}`, `<form class="band"><div><h2>The letter</h2><p class="lede">No ads. Just the rooms.</p></div><label class="fld">Email<input type="email" required></label></form>`),
      v("minimal-newsletter", "Minimal signup", "stack", "sharp", `form{max-width:360px;padding:16px;display:grid;gap:8px}`, `<form><label class="fld">Email for the journal<input type="email" required></label><button class="btn gh" type="submit">Send it</button></form>`),
    ]),
  ];

  function svgBigger() {
    return I.arrow;
  }
};
