"use strict";

module.exports = function chrome({ img, I, JS }) {
  const v = (slug, title, layout, family, css, html, js = "") => ({
    slug, title, layout, family, css, html, js,
  });

  const groups = [
    {
      category: "navigation",
      role: "navigation",
      pageReady: true,
      slots: ["wordmark", "nav-links", "cta"],
      variants: [
        v("island-nav", "Island navigation", "nav-bar", "editorial",
          `.skip{position:absolute;left:-999px}.skip:focus{left:12px;top:12px;background:var(--surface);padding:8px 12px;z-index:6}.nav{position:sticky;top:0;z-index:5;padding:14px 0}.bar{width:min(860px,calc(100% - 28px));margin:auto;display:flex;align-items:center;gap:14px;padding:8px 8px 8px 18px;background:color-mix(in srgb,var(--surface) 84%,transparent);border:1px solid var(--line);border-radius:var(--r);backdrop-filter:blur(14px);box-shadow:var(--sh)}.brand{font-size:1.3rem}.links{display:flex;gap:16px;margin-left:auto;color:var(--muted)}.links a{min-height:44px;display:inline-flex;align-items:center}.burger{display:none;width:48px;height:48px;border:0;border-radius:var(--r);background:transparent}@media(max-width:760px){.burger{display:grid;place-items:center;margin-left:auto}.links,.cta{display:none}.nav.is-open .links{display:flex;flex-direction:column;position:absolute;left:16px;right:16px;top:74px;padding:12px 16px;background:var(--surface);border:1px solid var(--line);border-radius:var(--r)}.nav.is-open .cta{display:inline-flex;margin:8px 16px 4px}}`,
          `<a class="skip" href="#content">Skip to content</a><header class="nav" data-nav><div class="bar"><a class="brand" href="#top">Northline</a><button class="burger" type="button" data-burger aria-expanded="false" aria-label="Open menu">${I.menu}</button><nav class="links" aria-label="Primary"><a href="#work">Work</a><a href="#services">Services</a><a href="#studio">Studio</a><a href="#visit">Visit</a></nav><a class="btn cta" href="#visit">Book</a></div></header><main id="content"></main>`,
          JS.nav),
        v("solid-bar-nav", "Solid bar navigation", "nav-bar", "studio",
          `.skip{position:absolute;left:-999px}.skip:focus{left:12px;top:12px;background:var(--surface);padding:8px 12px}.nav{position:sticky;top:0;z-index:5;background:var(--surface);border-bottom:1px solid var(--line)}.bar{display:flex;align-items:center;gap:18px;min-height:72px}.brand{font-size:1.35rem}.links{display:flex;gap:20px;margin-left:auto}.links a{min-height:44px;display:inline-flex;align-items:center}.burger{display:none;margin-left:auto;width:48px;height:48px;border:1px solid var(--line);border-radius:var(--r);background:transparent;color:inherit}@media(max-width:760px){.burger{display:grid;place-items:center}.links{display:none}.nav.is-open .links{display:flex;flex-direction:column;padding:8px 0 16px}}`,
          `<a class="skip" href="#content">Skip to content</a><header class="nav" data-nav><div class="w bar"><a class="brand" href="#top">Northline</a><button class="burger" type="button" data-burger aria-expanded="false" aria-label="Open menu">${I.menu}</button><nav class="links" aria-label="Primary"><a href="#work">Work</a><a href="#services">Services</a><a href="#journal">Journal</a><a href="#visit">Visit</a></nav><a class="btn" href="#visit">Start a project</a></div></header>`,
          JS.nav),
        v("text-link-nav", "Text link navigation", "nav-bar", "soft",
          `.nav{padding:22px 0 0}.bar{display:flex;align-items:flex-end;justify-content:space-between;gap:20px;padding-bottom:14px;border-bottom:1px solid var(--line)}.brand{font-size:1.8rem}.links{display:flex;gap:22px}.links a{min-height:44px;display:inline-flex;align-items:center;border-bottom:1px solid transparent}.links a:hover{border-color:var(--ink)}.burger{display:none;width:48px;height:48px;border:0;background:transparent}@media(max-width:760px){.bar{align-items:center}.burger{display:grid;place-items:center}.links{display:none}.nav.is-open .links{display:flex;flex-direction:column;padding-top:8px}}`,
          `<header class="nav" data-nav><div class="w bar"><a class="brand" href="#top">Northline</a><button class="burger" type="button" data-burger aria-expanded="false" aria-label="Open menu">${I.menu}</button><nav class="links" aria-label="Primary"><a href="#work">Work</a><a href="#about">About</a><a href="#visit">Visit</a></nav></div></header>`,
          JS.nav),
        v("centered-nav", "Centered navigation", "centered", "sharp",
          `.nav{padding:18px 0;border-bottom:1px solid var(--line);background:var(--surface)}.bar{display:grid;justify-items:center;gap:8px;text-align:center}.brand{font-size:1.15rem;letter-spacing:.18em;text-transform:uppercase}.links{display:flex;flex-wrap:wrap;gap:8px 18px;justify-content:center}.links a{min-height:44px;display:inline-flex;align-items:center;font-size:.92rem}`,
          `<header class="nav"><div class="w bar"><a class="brand" href="#top">Northline</a><nav class="links" aria-label="Primary"><a href="#work">Work</a><a href="#services">Services</a><a href="#studio">Studio</a><a href="#journal">Journal</a><a href="#visit">Visit</a></nav></div></header>`),
      ],
    },
    {
      category: "headers",
      role: "about",
      pageReady: true,
      slots: ["section-header", "body-copy"],
      variants: [
        v("centered-header", "Centered page header", "centered", "editorial",
          `.hd{padding:88px 0 36px;text-align:center}.hd .lede{margin:16px auto 0}`,
          `<header class="hd"><div class="w"><p class="ey">The studio</p><h1>Rooms with a point of view.</h1><p class="lede">Northline designs spaces, sites, and the quiet details between them.</p></div></header>`),
        v("split-header", "Split page header", "split-media", "studio",
          `.hd{padding:72px 0}.hd .g2{align-items:end}.lede{margin-top:14px}`,
          `<header class="hd"><div class="w g2"><div><p class="ey">Now booking</p><h1>Work that holds up in daylight.</h1></div><p class="lede">A small studio for homes, shops, and the brands that keep them.</p></div></header>`),
        v("rule-header", "Ruled page header", "band", "soft",
          `.hd{padding:64px 0 20px}.row{display:flex;justify-content:space-between;gap:20px;align-items:baseline;border-top:1px solid var(--line);padding-top:18px;margin-top:18px}.row span{color:var(--muted)}@media(max-width:800px){.row{flex-direction:column}}`,
          `<header class="hd"><div class="w"><p class="ey">Chapter 02</p><h1>How a visit works</h1><div class="row"><span>Consult, design, install</span><span>Usually four to six weeks</span></div></div></header>`),
        v("kicker-header", "Kicker page header", "stack", "sharp",
          `.hd{padding:48px 0 12px}h1{max-width:14ch}.meta{margin-top:18px;color:var(--muted)}`,
          `<header class="hd"><div class="w"><p class="ey">Field notes</p><h1>Materials we specify again.</h1><p class="meta">Oak, limewash, linen, and hardware you can repair.</p></div></header>`),
      ],
    },
    {
      category: "hero",
      role: "hero",
      pageReady: true,
      slots: ["headline", "subcopy", "cta", "media"],
      variants: [
        v("bleed-hero", "Full-bleed hero", "split-media", "editorial",
          `.hero{position:relative;min-height:100svh;display:grid;align-items:end;color:#f7f4ee}.hero img{position:absolute;inset:0;width:100%;height:100%;object-fit:cover}.shade{position:absolute;inset:0;background:linear-gradient(180deg,rgba(0,0,0,.15),rgba(0,0,0,.55))}.copy{position:relative;z-index:1;padding:0 0 56px}.copy h1{max-width:12ch}.copy .lede{color:#efeae2;margin:12px 0 22px}`,
          `<section class="hero">${img(1, "Sunlit living room with linen seating")}<div class="shade"></div><div class="w copy"><p class="ey">Northline</p><h1>Made to be lived in.</h1><p class="lede">Homes and shops, composed slowly.</p><div style="display:flex;gap:10px;flex-wrap:wrap"><a class="btn" href="#visit">Book a visit</a><a class="btn gh" href="#work" style="color:#fff;border-color:rgba(255,255,255,.4)">See the work</a></div></div></section>`),
        v("split-hero", "Split media hero", "split-media", "studio",
          `.hero{display:grid;grid-template-columns:1.05fr .95fr;min-height:100svh}.copy{display:flex;flex-direction:column;justify-content:center;padding:48px;gap:16px}.copy h1{max-width:11ch}.hero img{width:100%;height:100%;object-fit:cover}@media(max-width:800px){.hero{grid-template-columns:1fr;min-height:auto}.hero img{min-height:320px}.copy{padding:32px 20px 48px}}`,
          `<section class="hero"><div class="copy"><p class="ey">Studio</p><h1>Build the room you meant.</h1><p class="lede">Design, materials, and the crew to finish it.</p><div style="display:flex;gap:10px;flex-wrap:wrap"><a class="btn" href="#visit">Start a project</a><a class="btn gh" href="#work">View work</a></div></div>${img(0, "Architectural interior with stone and wood")}</section>`),
        v("centered-hero", "Centered media hero", "centered", "soft",
          `.hero{position:relative;min-height:100svh;display:grid;place-items:center;text-align:center;color:#fffaf6}.hero img{position:absolute;inset:0;width:100%;height:100%;object-fit:cover}.shade{position:absolute;inset:0;background:rgba(42,28,22,.42)}.copy{position:relative;z-index:1;padding:32px 20px}.copy h1{margin:10px auto}.copy .lede{margin:0 auto 20px;color:#f3ebe3}`,
          `<section class="hero">${img(9, "Soft morning light across a table")}<div class="shade"></div><div class="copy"><p class="ey">Northline</p><h1>A calmer way to begin.</h1><p class="lede">One conversation. A clear plan.</p><a class="btn" href="#visit">Reserve a time</a></div></section>`),
        v("asymmetric-hero", "Asymmetric hero", "split-media", "sharp",
          `.hero{display:grid;grid-template-columns:1.2fr .8fr;min-height:92svh;background:var(--surface)}.copy{padding:48px 28px 48px 6vw;display:flex;flex-direction:column;justify-content:flex-end;gap:14px}.hero figure{margin:0;min-height:420px}.hero img{width:100%;height:100%;object-fit:cover}@media(max-width:800px){.hero{grid-template-columns:1fr}.copy{padding:32px 20px}}`,
          `<section class="hero"><div class="copy"><p class="ey">01 — Practice</p><h1>Less noise. Better rooms.</h1><p class="lede">Northline for residential and retail.</p><a class="btn" href="#work">Enter the work ${I.arrow}</a></div><figure>${img(7, "Quiet office with a long table")}</figure></section>`),
      ],
    },
    {
      category: "features",
      role: "services",
      pageReady: true,
      slots: ["section-header", "cards", "media"],
      variants: [
        v("image-feature-grid", "Image feature grid", "card-grid", "editorial",
          `.card{background:var(--surface);border-radius:var(--r);overflow:hidden;box-shadow:var(--sh)}.card img{aspect-ratio:4/3;object-fit:cover;width:100%}.card div{padding:16px 16px 18px}.card h3{font-size:1.25rem;margin-bottom:6px}.head{margin-bottom:28px}`,
          `<section class="block"><div class="w"><div class="head"><p class="ey">Services</p><h2>Three ways we help.</h2></div><div class="g3"><article class="card">${img(2, "Craftsperson measuring timber")}<div><h3>Consult</h3><p class="lede">A site visit and a written plan.</p></div></article><article class="card">${img(5, "Hands finishing a material sample")}<div><h3>Design</h3><p class="lede">Drawings, samples, and a budget.</p></div></article><article class="card">${img(6, "Storefront ready for opening")}<div><h3>Install</h3><p class="lede">One crew from demo to last detail.</p></div></article></div></div></section>`),
        v("alternating-features", "Alternating features", "alternating", "studio",
          `.row{display:grid;grid-template-columns:1fr 1fr;gap:28px;align-items:center;margin-top:36px}.row img{border-radius:var(--r);aspect-ratio:5/4;object-fit:cover;width:100%}.row:nth-child(even) .copy{order:-1}@media(max-width:800px){.row,.row:nth-child(even) .copy{order:0}.row{grid-template-columns:1fr}}`,
          `<section class="block"><div class="w"><p class="ey">What we do</p><h2>Practical, then beautiful.</h2><div class="row">${img(0, "Interior with a plaster wall")}<div class="copy"><h3>Interiors</h3><p class="lede">Kitchens, baths, and the rooms between.</p></div></div><div class="row">${img(6, "Retail interior at dusk")}<div class="copy"><h3>Shops</h3><p class="lede">Fixtures, lighting, and a floor that works.</p></div></div></div></section>`),
        v("bento-features", "Bento features", "bento", "soft",
          `.bento{display:grid;grid-template-columns:1.3fr .7fr;gap:14px;margin-top:24px}.bento article{background:var(--surface);border-radius:var(--r);padding:20px;border:1px solid var(--line)}.span img{width:100%;height:180px;object-fit:cover;border-radius:12px;margin-bottom:12px}.side{display:grid;gap:14px}@media(max-width:800px){.bento{grid-template-columns:1fr}}`,
          `<section class="block"><div class="w"><p class="ey">Offer</p><h2>A small menu, done well.</h2><div class="bento"><article class="span">${img(3, "Coffee service on a wood counter")}<h3>Daily service</h3><p class="lede">Maintenance plans for spaces we already know.</p></article><div class="side"><article><h3>One-day refresh</h3><p class="lede">Paint, hardware, lighting.</p></article><article><h3>Full remodel</h3><p class="lede">From first sketch to walkthrough.</p></article></div></div></div></section>`),
        v("numbered-features", "Numbered features", "numbered-list", "sharp",
          `.list{margin-top:28px;border-top:1px solid var(--line)}.item{display:grid;grid-template-columns:72px 1fr 1.2fr;gap:16px;padding:20px 0;border-bottom:1px solid var(--line)}.num{font-family:var(--d);font-size:1.4rem}@media(max-width:800px){.item{grid-template-columns:48px 1fr}}`,
          `<section class="block"><div class="w"><p class="ey">Process</p><h2>Four clear steps.</h2><div class="list"><div class="item"><span class="num">01</span><h3>Listen</h3><p class="lede">We walk the space and write the brief.</p></div><div class="item"><span class="num">02</span><h3>Propose</h3><p class="lede">A plan, a palette, and a number.</p></div><div class="item"><span class="num">03</span><h3>Build</h3><p class="lede">Weekly updates. No mystery invoices.</p></div><div class="item"><span class="num">04</span><h3>Hand off</h3><p class="lede">A punch list and a care guide.</p></div></div></div></section>`),
      ],
    },
    {
      category: "cards",
      role: "services",
      pageReady: true,
      slots: ["section-header", "cards", "media"],
      variants: [
        v("media-cards", "Media cards", "card-grid", "editorial",
          `article{background:var(--surface);border-radius:var(--r);overflow:hidden}article img{aspect-ratio:3/2;object-fit:cover;width:100%}article div{padding:16px}h3{font-size:1.2rem;margin-bottom:6px}`,
          `<section class="block"><div class="w"><p class="ey">Selected</p><h2>Recent rooms</h2><div class="g3" style="margin-top:22px"><article>${img(0, "Limewashed living room")}<div><h3>Hill house</h3><p class="lede">Living, kitchen, stair.</p></div></article><article>${img(7, "Long communal table")}<div><h3>Atelier</h3><p class="lede">A workroom for eight.</p></div></article><article>${img(6, "Evening storefront")}<div><h3>Market</h3><p class="lede">Fixtures and a new front.</p></div></article></div></div></section>`),
        v("horizontal-cards", "Horizontal cards", "flex-row", "studio",
          `article{display:grid;grid-template-columns:160px 1fr;gap:16px;padding:12px;background:var(--surface);border-radius:var(--r);border:1px solid var(--line);margin-top:12px}img{width:160px;height:120px;object-fit:cover;border-radius:8px}@media(max-width:800px){article{grid-template-columns:1fr}img{width:100%}}`,
          `<section class="block"><div class="w"><h2>On the board</h2><article>${img(2, "Workshop bench")}<div><h3>Oak stair</h3><p class="lede">Treads, rail, and a quieter landing.</p></div></article><article>${img(5, "Material samples")}<div><h3>Sample set</h3><p class="lede">Three finishes, one direction.</p></div></article></div></section>`),
        v("overlay-cards", "Overlay cards", "card-grid", "soft",
          `article{position:relative;min-height:280px;border-radius:var(--r);overflow:hidden;color:#fff}article img{position:absolute;inset:0;width:100%;height:100%;object-fit:cover}article div{position:absolute;left:0;right:0;bottom:0;padding:16px;background:linear-gradient(transparent,rgba(0,0,0,.62))}`,
          `<section class="block"><div class="w g2"><article>${img(1, "House exterior in warm light")}<div><h3>Residences</h3><p>Whole-home composition.</p></div></article><article>${img(8, "Set dining table")}<div><h3>Hospitality</h3><p>Rooms people stay in.</p></div></article></div></section>`),
        v("quiet-cards", "Quiet text cards", "card-grid", "sharp",
          `article{border:1px solid var(--line);padding:20px;background:var(--surface);min-height:180px;display:flex;flex-direction:column;justify-content:space-between}h3{font-size:1.35rem}`,
          `<section class="block"><div class="w"><div class="g3"><article><p class="ey">01</p><h3>Advice</h3><p class="lede">An hour on site.</p></article><article><p class="ey">02</p><h3>Drawings</h3><p class="lede">Plans you can price.</p></article><article><p class="ey">03</p><h3>Build</h3><p class="lede">We stay through the end.</p></article></div></div></section>`),
      ],
    },
    {
      category: "galleries",
      role: "gallery",
      pageReady: true,
      slots: ["section-header", "media"],
      variants: [
        v("grid-gallery", "Grid gallery", "card-grid", "editorial",
          `.gal{display:grid;grid-template-columns:1.4fr 1fr 1fr;gap:10px;margin-top:20px}.gal img{width:100%;height:100%;object-fit:cover;border-radius:var(--r)}.gal img:first-child{grid-row:span 2;min-height:420px}@media(max-width:800px){.gal{grid-template-columns:1fr 1fr}.gal img:first-child{grid-row:auto;min-height:220px}}`,
          `<section class="block"><div class="w"><p class="ey">Portfolio</p><h2>A few rooms.</h2><div class="gal">${img(0, "Living room")}${img(1, "Exterior")}${img(7, "Work table")}${img(3, "Counter")}${img(6, "Shop")}</div></div></section>`),
        v("masonry-gallery", "Masonry gallery", "card-grid", "studio",
          `.gal{columns:3;gap:12px;margin-top:18px}.gal img{width:100%;margin:0 0 12px;border-radius:10px}@media(max-width:800px){.gal{columns:2}}`,
          `<section class="block"><div class="w"><h2>Site photos</h2><div class="gal">${img(2, "Construction detail")}${img(5, "Hands at work")}${img(9, "Landscape light")}${img(8, "Table setting")}${img(4, "Portrait in the studio")}</div></div></section>`),
        v("featured-gallery", "Featured gallery", "split-media", "soft",
          `.gal{display:grid;grid-template-columns:1.4fr .8fr;gap:12px;margin-top:18px}.side{display:grid;gap:12px}.gal img{width:100%;height:100%;object-fit:cover;border-radius:var(--r);min-height:180px}@media(max-width:800px){.gal{grid-template-columns:1fr}}`,
          `<section class="block"><div class="w"><h2>This season</h2><div class="gal">${img(1, "Featured house")}<div class="side">${img(3, "Cafe detail")}${img(0, "Seating")}</div></div></div></section>`),
        v("filmstrip-gallery", "Filmstrip gallery", "marquee", "sharp",
          `.strip{display:flex;gap:10px;overflow:auto;scroll-snap-type:x mandatory;padding-bottom:8px;margin-top:16px}.strip img{width:min(70vw,420px);height:280px;object-fit:cover;flex:none;scroll-snap-align:start}`,
          `<section class="block"><div class="w"><p class="ey">Scroll</p><h2>Along the job.</h2></div><div class="strip" tabindex="0" aria-label="Project photos">${img(2, "Framing")}${img(5, "Finish work")}${img(6, "Opening day")}${img(7, "Furniture plan")}</div></section>`),
      ],
    },
    {
      category: "testimonials",
      role: "testimonials",
      pageReady: true,
      slots: ["section-header", "proof-items"],
      variants: [
        v("quote-cards", "Quote cards", "card-grid", "editorial",
          `figure{margin:0;background:var(--surface);border-radius:var(--r);padding:22px;box-shadow:var(--sh)}blockquote{font-family:var(--d);font-size:1.35rem;line-height:1.25;margin:0 0 16px}figcaption{color:var(--muted)}`,
          `<section class="block"><div class="w"><p class="ey">Clients</p><h2>In their words.</h2><div class="g3" style="margin-top:22px"><figure><blockquote>“They left the house calmer than they found it.”</blockquote><figcaption>Mara Ellison, homeowner</figcaption></figure><figure><blockquote>“The shop opened on the day they named.”</blockquote><figcaption>Jon Park, retailer</figcaption></figure><figure><blockquote>“Clear budget. No theater.”</blockquote><figcaption>Adele Cho, founder</figcaption></figure></div></div></section>`),
        v("large-quote", "Large quote", "centered", "studio",
          `figure{margin:0;max-width:18em}blockquote{font-family:var(--d);font-size:clamp(2rem,4vw,3.2rem);line-height:1.12;margin:0 0 16px}`,
          `<section class="block"><div class="w"><figure><blockquote>“We finally have a room that matches the work.”</blockquote><figcaption class="lede">Elena Voss, studio director</figcaption></figure></div></section>`),
        v("split-quote", "Split quote", "split-media", "soft",
          `.q{display:grid;grid-template-columns:.8fr 1.2fr;gap:28px;align-items:center}.q img{border-radius:var(--r);aspect-ratio:1;object-fit:cover;width:100%}blockquote{font-family:var(--d);font-size:clamp(1.6rem,3vw,2.3rem);line-height:1.2;margin:0 0 12px}@media(max-width:800px){.q{grid-template-columns:1fr}}`,
          `<section class="block"><div class="w q">${img(4, "Portrait of a client in the finished room")}<figure><blockquote>“I walk in and the day gets quieter.”</blockquote><figcaption class="lede">Chris Adelman</figcaption></figure></div></section>`),
        v("quote-list", "Quote list", "stack", "sharp",
          `article{display:grid;grid-template-columns:180px 1fr;gap:16px;padding:18px 0;border-top:1px solid var(--line)}@media(max-width:800px){article{grid-template-columns:1fr}}`,
          `<section class="block"><div class="w"><h2>Notes</h2><div style="margin-top:12px"><article><strong>Hill house</strong><p>“The stair is the thing guests touch first.”</p></article><article><strong>Market</strong><p>“Lighting finally matches the product.”</p></article><article><strong>Atelier</strong><p>“Eight people, and it still feels open.”</p></article></div></div></section>`),
      ],
    },
    {
      category: "pricing",
      role: "pricing",
      pageReady: true,
      slots: ["section-header", "cards"],
      variants: [
        v("three-tiers", "Three price tiers", "card-grid", "editorial",
          `article{background:var(--surface);border:1px solid var(--line);border-radius:var(--r);padding:20px;display:flex;flex-direction:column;gap:10px}.price{font-family:var(--d);font-size:2.2rem}ul{margin:8px 0 16px;padding-left:18px;color:var(--muted)}.feat{background:var(--ink);color:var(--on)}.feat .btn{background:var(--on);color:var(--ink)}`,
          `<section class="block"><div class="w"><p class="ey">Fees</p><h2>Start where you are.</h2><div class="g3" style="margin-top:22px"><article><h3>Consult</h3><p class="price">$480</p><ul><li>Site visit</li><li>Written notes</li></ul><a class="btn gh" href="#visit">Book</a></article><article class="feat"><h3>Design</h3><p class="price">$4,800</p><ul><li>Drawings</li><li>Samples</li><li>Budget</li></ul><a class="btn" href="#visit">Begin</a></article><article><h3>Build</h3><p class="price">Custom</p><ul><li>Crew</li><li>Weekly updates</li></ul><a class="btn gh" href="#visit">Talk</a></article></div></div></section>`),
        v("two-tiers", "Two price tiers", "card-grid", "studio",
          `article{padding:28px;border-radius:var(--r);background:var(--surface);border:1px solid var(--line)}.price{font-size:2rem;font-family:var(--d);margin:8px 0}`,
          `<section class="block"><div class="w g2"><article><p class="ey">Half day</p><h3>Review</h3><p class="price">$900</p><p class="lede">Walkthrough and a priority list.</p><a class="btn" href="#visit" style="margin-top:16px">Schedule</a></article><article><p class="ey">Retainer</p><h3>Season</h3><p class="price">$2,400</p><p class="lede">Four visits and a direct line.</p><a class="btn gh" href="#visit" style="margin-top:16px">Ask</a></article></div></section>`),
        v("single-offer", "Single offer", "band", "soft",
          `.offer{background:var(--surface);border-radius:var(--r);padding:28px;display:flex;justify-content:space-between;gap:20px;align-items:center;border:1px solid var(--line)}@media(max-width:800px){.offer{flex-direction:column;align-items:flex-start}}`,
          `<section class="block"><div class="w offer"><div><p class="ey">Spring</p><h2>Kitchen plan</h2><p class="lede">Measured drawings and a finish schedule. $3,200.</p></div><a class="btn" href="#visit">Request the plan</a></div></section>`),
        v("price-list", "Service price list", "numbered-list", "sharp",
          `.row{display:flex;justify-content:space-between;gap:16px;padding:16px 0;border-bottom:1px solid var(--line)}`,
          `<section class="block"><div class="w"><h2>Menu</h2><div style="margin-top:10px"><div class="row"><span>Hourly advice</span><strong>$180</strong></div><div class="row"><span>Room design</span><strong>$2,600</strong></div><div class="row"><span>Full home</span><strong>From $9,500</strong></div></div></div></section>`),
      ],
    },
    {
      category: "cta",
      role: "cta_band",
      pageReady: true,
      slots: ["headline", "cta"],
      variants: [
        v("band-cta", "Contrast band", "band", "editorial",
          `.band{background:var(--ink);color:var(--on);padding:64px 0}.band .btn{background:var(--on);color:var(--ink)}`,
          `<section class="band"><div class="w" style="display:flex;justify-content:space-between;gap:18px;align-items:center;flex-wrap:wrap"><h2>Ready when you are.</h2><a class="btn" href="#visit">Book a visit</a></div></section>`),
        v("split-cta", "Split image call to action", "split-media", "studio",
          `.cta{display:grid;grid-template-columns:1fr 1fr}.cta img{min-height:280px;object-fit:cover;width:100%;height:100%}.copy{padding:40px;display:flex;flex-direction:column;justify-content:center;gap:12px}@media(max-width:800px){.cta{grid-template-columns:1fr}}`,
          `<section class="cta">${img(9, "Open landscape at dusk")}<div class="copy"><h2>Come see the studio.</h2><p class="lede">Thursdays, by appointment.</p><a class="btn" href="#visit">Choose a time</a></div></section>`),
        v("quiet-cta", "Quiet centered call to action", "centered", "soft",
          `.cta{text-align:center;padding:80px 20px}.cta .lede{margin:12px auto 20px}`,
          `<section class="cta"><p class="ey">Next</p><h2>Tell us about the room.</h2><p class="lede">A short note is enough to begin.</p><a class="btn" href="#visit">Write to us</a></section>`),
        v("inline-cta", "Inline call to action", "flex-row", "sharp",
          `.cta{display:flex;justify-content:space-between;gap:16px;align-items:center;padding:28px 0;border-top:1px solid var(--line);border-bottom:1px solid var(--line)}@media(max-width:800px){.cta{flex-direction:column;align-items:flex-start}}`,
          `<section class="block"><div class="w cta"><div><h2>Start with a walkthrough.</h2><p class="lede">We reply within one business day.</p></div><a class="btn" href="#visit">Request a visit ${I.arrow}</a></div></section>`),
      ],
    },
    {
      category: "forms",
      role: "contact_form",
      pageReady: true,
      slots: ["section-header", "form-fields", "cta"],
      variants: [
        v("stacked-form", "Stacked contact form", "form-stack", "editorial",
          `form{display:grid;gap:14px;max-width:560px;margin-top:20px}.err{color:#8f2d2d;font-size:.85rem}`,
          `<section class="block" id="visit"><div class="w"><p class="ey">Visit</p><h2>Tell us the project.</h2><form><label class="fld">Name<input name="name" required autocomplete="name"></label><label class="fld">Email<input type="email" name="email" required autocomplete="email"></label><label class="fld">Phone<input type="tel" name="phone" autocomplete="tel"></label><label class="fld">About the work<textarea name="message" required></textarea><span class="hint">A sentence or two is plenty.</span></label><button class="btn" type="submit">Send</button></form></div></section>`),
        v("split-form", "Split contact form", "split-media", "studio",
          `.box{align-items:start}.aside{display:grid;gap:12px;color:var(--muted)}form{display:grid;gap:12px}`,
          `<section class="block" id="visit"><div class="w g2 box"><div class="aside"><p class="ey">Contact</p><h2>Write or call.</h2><p>${I.phone} (415) 555-0148</p><p>${I.pin} 18 Harbor Ave</p><p>${I.clock} Tue–Fri, 9–5</p></div><form><label class="fld">Name<input name="name" required autocomplete="name"></label><label class="fld">Email<input type="email" name="email" required autocomplete="email"></label><label class="fld">Message<textarea name="message" required></textarea></label><button class="btn" type="submit">Send message</button></form></div></section>`),
        v("two-column-form", "Two-column contact form", "form-stack", "soft",
          `form{display:grid;gap:14px;margin-top:18px}.pair{display:grid;grid-template-columns:1fr 1fr;gap:12px}@media(max-width:800px){.pair{grid-template-columns:1fr}}`,
          `<section class="block" id="visit"><div class="w"><h2>Request a consult</h2><form><div class="pair"><label class="fld">First name<input name="given-name" autocomplete="given-name" required></label><label class="fld">Last name<input name="family-name" autocomplete="family-name" required></label></div><label class="fld">Email<input type="email" name="email" autocomplete="email" required></label><label class="fld">What do you need?<textarea name="message" required></textarea></label><button class="btn" type="submit">Submit</button></form></div></section>`),
        v("panel-form", "Panel contact form", "form-stack", "sharp",
          `.panel{background:var(--surface);border:1px solid var(--line);padding:24px;max-width:640px}form{display:grid;gap:12px;margin-top:12px}`,
          `<section class="block" id="visit"><div class="w"><div class="panel"><h2>Start a note</h2><form><label class="fld">Email<input type="email" name="email" required autocomplete="email"></label><label class="fld">Project<textarea name="message" required placeholder="Room, timeline, neighborhood"></textarea></label><button class="btn" type="submit">Send</button></form></div></div></section>`),
      ],
    },
    {
      category: "contact",
      role: "contact_form",
      pageReady: true,
      slots: ["section-header", "form-fields", "contact-facts", "cta"],
      variants: [
        v("details-contact", "Contact with details", "split-media", "editorial",
          `.card{background:var(--surface);border-radius:var(--r);padding:22px;box-shadow:var(--sh)}form{display:grid;gap:12px}li{list-style:none;display:flex;gap:8px;align-items:center;min-height:36px}ul{margin:16px 0 0;padding:0}`,
          `<section class="block"><div class="w g2"><div><p class="ey">Studio</p><h2>Come by or write.</h2><ul><li>${I.pin} 18 Harbor Ave</li><li>${I.phone} (415) 555-0148</li><li>${I.clock} Tue–Fri, 9–5</li><li>${I.mail} hello@northline.example</li></ul></div><form class="card"><label class="fld">Name<input name="name" required autocomplete="name"></label><label class="fld">Email<input type="email" name="email" required autocomplete="email"></label><label class="fld">Message<textarea name="message" required></textarea></label><button class="btn" type="submit">Send</button></form></div></section>`),
        v("mapless-contact", "Address and form", "multi-column", "studio",
          `form{display:grid;gap:12px}.facts{display:grid;gap:8px;margin-top:16px}`,
          `<section class="block"><div class="w"><h2>Contact</h2><div class="g2" style="margin-top:18px"><div class="facts"><p>18 Harbor Ave, Suite 2</p><p>(415) 555-0148</p><p>hello@northline.example</p></div><form><label class="fld">Email<input type="email" required name="email" autocomplete="email"></label><label class="fld">How can we help?<textarea required name="message"></textarea></label><button class="btn" type="submit">Send</button></form></div></div></section>`),
        v("card-contact", "Card contact section", "form-stack", "soft",
          `.shell{background:var(--surface);border-radius:calc(var(--r) + 6px);padding:28px;border:1px solid var(--line)}form{display:grid;gap:12px;margin-top:12px}`,
          `<section class="block"><div class="w shell"><p class="ey">Hello</p><h2>We read every note.</h2><form><label class="fld">Name<input name="name" autocomplete="name" required></label><label class="fld">Phone<input name="phone" type="tel" autocomplete="tel"></label><label class="fld">Note<textarea name="message" required></textarea></label><button class="btn" type="submit">Send note</button></form></div></section>`),
        v("hours-contact", "Contact beside hours", "split-media", "sharp",
          `form{display:grid;gap:12px}.hrs{border-top:1px solid var(--line)} .hrs div{display:flex;justify-content:space-between;padding:8px 0;border-bottom:1px solid var(--line)}`,
          `<section class="block"><div class="w g2"><form><h2>Write</h2><label class="fld">Email<input type="email" name="email" required autocomplete="email"></label><label class="fld">Message<textarea name="message" required></textarea></label><button class="btn" type="submit">Send</button></form><div><h2>Hours</h2><div class="hrs"><div><span>Tue–Fri</span><span>9–5</span></div><div><span>Sat</span><span>10–2</span></div><div><span>Sun–Mon</span><span>Closed</span></div></div></div></div></section>`),
      ],
    },
    {
      category: "footers",
      role: "footer",
      pageReady: true,
      slots: ["wordmark", "links", "contact-facts"],
      variants: [
        v("columns-footer", "Multi-column footer", "multi-column", "editorial",
          `footer{background:var(--ink);color:var(--on);padding:48px 0 24px}a{color:inherit}nav{display:grid;gap:8px}.top{display:grid;grid-template-columns:1.3fr repeat(3,1fr);gap:20px}.brand{font-size:1.8rem}.legal{margin-top:28px;color:color-mix(in srgb,var(--on) 70%,transparent);font-size:.9rem}@media(max-width:800px){.top{grid-template-columns:1fr 1fr}}`,
          `<footer><div class="w"><div class="top"><div><a class="brand" href="#top">Northline</a><p class="legal">18 Harbor Ave<br>(415) 555-0148</p></div><nav aria-label="Work"><a href="#work">Work</a><a href="#services">Services</a><a href="#journal">Journal</a></nav><nav aria-label="Studio"><a href="#about">About</a><a href="#visit">Visit</a><a href="#visit">Contact</a></nav><nav aria-label="Hours"><span>Tue–Fri 9–5</span><span>Sat 10–2</span></nav></div><p class="legal">© Northline. All rights reserved.</p></div></footer>`),
        v("minimal-footer", "Minimal footer", "band", "studio",
          `footer{padding:22px 0;border-top:1px solid var(--line)}.row{display:flex;justify-content:space-between;gap:12px;flex-wrap:wrap;align-items:center}.links{display:flex;gap:16px}`,
          `<footer><div class="w row"><a class="brand" href="#top">Northline</a><nav class="links" aria-label="Footer"><a href="#work">Work</a><a href="#visit">Visit</a><a href="#visit">Contact</a></nav><span class="lede">(415) 555-0148</span></div></footer>`),
        v("newsletter-footer", "Footer with note line", "multi-column", "soft",
          `footer{padding:40px 0;background:var(--surface);border-top:1px solid var(--line)}.row{display:flex;justify-content:space-between;gap:20px;flex-wrap:wrap}.links{display:flex;gap:14px;align-items:center}`,
          `<footer><div class="w"><div class="row"><div><p class="brand" style="font-size:2rem">Northline</p><p class="lede">18 Harbor Ave · Tue–Fri</p></div><nav class="links" aria-label="Footer"><a href="#services">Services</a><a href="#work">Work</a><a href="#visit">Book</a></nav></div></div></footer>`),
        v("facts-footer", "Contact facts footer", "stack", "sharp",
          `footer{padding:36px 0;border-top:1px solid var(--line)}.grid{display:grid;grid-template-columns:1.4fr repeat(3,1fr);gap:12px;margin-top:16px}@media(max-width:800px){.grid{grid-template-columns:1fr 1fr}}`,
          `<footer><div class="w"><a class="brand" href="#top">Northline</a><div class="grid"><p>18 Harbor Ave<br>Suite 2</p><p>(415) 555-0148<br>hello@northline.example</p><p>Tue–Fri 9–5<br>Sat 10–2</p><nav style="display:grid;gap:6px" aria-label="Footer"><a href="#work">Work</a><a href="#about">About</a><a href="#visit">Visit</a></nav></div></div></footer>`),
      ],
    },
    {
      category: "faqs",
      role: "faq",
      pageReady: true,
      slots: ["section-header", "faq-items"],
      variants: [
        v("faq-single", "Single-open FAQ", "stack", "editorial",
          `.item{border-bottom:1px solid var(--line)}button{width:100%;min-height:56px;display:flex;justify-content:space-between;gap:12px;align-items:center;background:none;border:0;text-align:left;font-weight:700}.item div{padding:0 0 16px;color:var(--muted)}`,
          `<section class="block"><div class="w" data-acc><p class="ey">Questions</p><h2>Before you visit.</h2><div class="item"><button type="button" aria-expanded="true">How long is a consult? ${I.chev}</button><div>About ninety minutes on site, then notes the next day.</div></div><div class="item"><button type="button" aria-expanded="false">Do you build? ${I.chev}</button><div hidden>Yes. Design-only is also available.</div></div><div class="item"><button type="button" aria-expanded="false">Where do you work? ${I.chev}</button><div hidden>The city and a short drive beyond the bridge.</div></div></div></section>`,
          JS.acc),
        v("faq-two-col", "Two-column FAQ", "multi-column", "studio",
          `.item{padding:16px 0;border-top:1px solid var(--line)}h3{font-size:1.15rem;margin-bottom:6px}`,
          `<section class="block"><div class="w"><h2>FAQ</h2><div class="g2" style="margin-top:16px"><article class="item"><h3>Lead time?</h3><p class="lede">Design books about three weeks out.</p></article><article class="item"><h3>Deposits?</h3><p class="lede">Half to begin drawings.</p></article><article class="item"><h3>Permits?</h3><p class="lede">We prepare the set. You submit, or we can.</p></article><article class="item"><h3>Warranties?</h3><p class="lede">One year on our workmanship.</p></article></div></div></section>`),
        v("faq-bordered", "Bordered FAQ", "card-grid", "soft",
          `.item{background:var(--surface);border:1px solid var(--line);border-radius:var(--r);padding:16px 18px;margin-top:10px}h3{margin-bottom:6px}`,
          `<section class="block"><div class="w" style="max-width:760px"><h2>Good to know</h2><article class="item"><h3>Can I bring a contractor?</h3><p class="lede">Yes. We are glad to coordinate.</p></article><article class="item"><h3>Do you source furniture?</h3><p class="lede">When it serves the room, yes.</p></article></div></section>`),
        v("faq-plus", "Plus icon FAQ", "stack", "sharp",
          `button{width:100%;display:flex;justify-content:space-between;align-items:center;gap:12px;min-height:52px;background:none;border:0;border-bottom:1px solid var(--line);font-weight:650;text-align:left}.panel{padding:12px 0 16px;color:var(--muted)}`,
          `<section class="block"><div class="w" data-acc style="max-width:720px"><h2>FAQ</h2><button type="button" aria-expanded="false">What should I prepare? ${I.plus}</button><div class="panel" hidden>Photos, a rough budget, and the deadline that matters.</div><button type="button" aria-expanded="true">Is the first call free? ${I.plus}</button><div class="panel">A fifteen-minute call is free. Site visits are scheduled.</div></div></section>`,
          JS.acc),
      ],
    },
    {
      category: "accordions",
      role: "faq",
      pageReady: true,
      slots: ["section-header", "faq-items"],
      variants: [
        v("line-accordion", "Line accordion", "stack", "editorial",
          `button{width:100%;text-align:left;background:none;border:0;border-top:1px solid var(--line);min-height:52px;font-weight:700}.panel{padding-bottom:14px;color:var(--muted)}`,
          `<div class="w block" data-acc><button type="button" aria-expanded="true">Materials</button><div class="panel">We specify finishes you can repair.</div><button type="button" aria-expanded="false">Timeline</button><div class="panel" hidden>Small rooms land in about a month.</div></div>`,
          JS.acc),
        v("card-accordion", "Card accordion", "card-grid", "soft",
          `.item{background:var(--surface);border-radius:var(--r);margin-bottom:10px;border:1px solid var(--line)}button{width:100%;text-align:left;background:none;border:0;min-height:52px;padding:0 16px;font-weight:700}.panel{padding:0 16px 14px;color:var(--muted)}`,
          `<div class="w block" data-acc><div class="item"><button type="button" aria-expanded="true">Scope</button><div class="panel">One room or the whole floor.</div></div><div class="item"><button type="button" aria-expanded="false">Travel</button><div class="panel" hidden>Within an hour of the studio.</div></div></div>`,
          JS.acc),
        v("icon-accordion", "Icon accordion", "stack", "studio",
          `button{width:100%;display:flex;gap:10px;align-items:center;background:none;border:0;border-bottom:1px solid var(--line);min-height:56px;color:inherit;font-weight:650}.panel{padding:8px 0 16px 30px;color:var(--muted)}`,
          `<div class="w block" data-acc><button type="button" aria-expanded="true">${I.info} Care</button><div class="panel">A printed guide leaves with the keys.</div><button type="button" aria-expanded="false">${I.clock} Scheduling</button><div class="panel" hidden>We hold one job at a time per lead.</div></div>`,
          JS.acc),
        v("stacked-accordion", "Stacked accordion", "stack", "sharp",
          `details{border-bottom:1px solid var(--line);padding:8px 0}summary{min-height:48px;display:flex;align-items:center;cursor:pointer;font-weight:650}p{color:var(--muted);margin:0 0 10px}`,
          `<div class="w block"><details open><summary>What is included?</summary><p>Drawings, a finish list, and two revisions.</p></details><details><summary>What is not?</summary><p>Permits fees and appliances, unless asked.</p></details></div>`),
      ],
    },
    {
      category: "maps",
      role: "map",
      pageReady: true,
      slots: ["map", "contact-facts"],
      variants: [
        v("embed-map", "Embedded map", "split-media", "editorial",
          `.map{display:grid;grid-template-columns:1.3fr .7fr;min-height:420px}iframe{width:100%;height:100%;min-height:320px;border:0}.card{padding:28px;background:var(--surface)}@media(max-width:800px){.map{grid-template-columns:1fr}}`,
          `<section class="map"><iframe title="Map showing 18 Harbor Ave" loading="lazy" referrerpolicy="no-referrer-when-downgrade" src="https://www.openstreetmap.org/export/embed.html?bbox=-122.431%2C37.775%2C-122.405%2C37.795&amp;layer=mapnik"></iframe><div class="card"><p class="ey">Visit</p><h2>The studio</h2><p class="lede">18 Harbor Ave, Suite 2</p><p class="lede">(415) 555-0148</p><a class="btn" href="https://www.openstreetmap.org" style="margin-top:16px">Open map</a></div></section>`),
        v("split-address-map", "Address beside map image", "split-media", "studio",
          `.map{display:grid;grid-template-columns:1fr 1fr}.map img{min-height:300px;object-fit:cover;width:100%;height:100%}.copy{padding:32px}@media(max-width:800px){.map{grid-template-columns:1fr}}`,
          `<section class="map">${img(9, "Neighborhood street in late light")}<div class="copy"><h2>Find us</h2><p class="lede">18 Harbor Ave. Street parking after 6.</p><p>${I.pin} Two blocks from the ferry.</p></div></section>`),
        v("card-map", "Map with pin card", "card-grid", "soft",
          `.frame{position:relative;border-radius:var(--r);overflow:hidden;min-height:380px}.frame iframe{width:100%;height:420px;border:0}.pin{position:absolute;left:16px;bottom:16px;background:var(--surface);padding:14px 16px;border-radius:var(--r);max-width:240px}`,
          `<section class="block"><div class="w frame"><iframe title="Studio map" loading="lazy" src="https://www.openstreetmap.org/export/embed.html?bbox=-122.425%2C37.778%2C-122.41%2C37.79&amp;layer=mapnik"></iframe><div class="pin"><strong>Northline</strong><p class="lede">18 Harbor Ave</p></div></div></section>`),
        v("hours-map", "Map and hours", "multi-column", "sharp",
          `.map iframe{width:100%;min-height:280px;border:1px solid var(--line)}.hrs div{display:flex;justify-content:space-between;padding:8px 0;border-bottom:1px solid var(--line)}`,
          `<section class="block"><div class="w g2"><iframe title="Map of the studio" loading="lazy" src="https://www.openstreetmap.org/export/embed.html?bbox=-122.43%2C37.776%2C-122.408%2C37.792&amp;layer=mapnik"></iframe><div><h2>Hours & place</h2><p class="lede">18 Harbor Ave</p><div class="hrs"><div><span>Tue–Fri</span><span>9–5</span></div><div><span>Sat</span><span>10–2</span></div></div></div></div></section>`),
      ],
    },
    {
      category: "hours",
      role: "hours_location",
      pageReady: true,
      slots: ["section-header", "contact-facts"],
      variants: [
        v("hours-table", "Hours table", "stack", "editorial",
          `table{width:100%;border-collapse:collapse;margin-top:16px}th,td{text-align:left;padding:12px 0;border-bottom:1px solid var(--line)}th{font-weight:600}`,
          `<section class="block"><div class="w" style="max-width:640px"><p class="ey">Visit</p><h2>Hours</h2><table><tbody><tr><th scope="row">Tuesday–Friday</th><td>9:00–5:00</td></tr><tr><th scope="row">Saturday</th><td>10:00–2:00</td></tr><tr><th scope="row">Sunday–Monday</th><td>Closed</td></tr></tbody></table></div></section>`),
        v("hours-split", "Hours beside address", "split-media", "studio",
          ``,
          `<section class="block"><div class="w g2"><div><p class="ey">Place</p><h2>18 Harbor Ave</h2><p class="lede">Suite 2, street level. Ring the studio bell.</p></div><div><p class="ey">Hours</p><p>Tue–Fri, 9–5</p><p>Sat, 10–2</p><p>Sun–Mon, closed</p></div></div></section>`),
        v("hours-card", "Hours card", "card-grid", "soft",
          `.card{background:var(--surface);border-radius:var(--r);padding:22px;border:1px solid var(--line)}`,
          `<section class="block"><div class="w g2"><article class="card"><h2>Open</h2><p class="lede">Tuesday to Friday, nine to five. Saturday mornings.</p></article><article class="card"><h2>Closed</h2><p class="lede">Sunday, Monday, and public holidays.</p></article></div></section>`),
        v("hours-stacked", "Stacked hours", "stack", "sharp",
          `.row{display:flex;justify-content:space-between;padding:14px 0;border-bottom:1px solid var(--line)}`,
          `<section class="block"><div class="w" style="max-width:520px"><h2>When we are in</h2><div class="row"><span>Tue–Fri</span><strong>9–5</strong></div><div class="row"><span>Saturday</span><strong>10–2</strong></div><div class="row"><span>Sunday</span><strong>Closed</strong></div></div></section>`),
      ],
    },
    {
      category: "team",
      role: "team",
      pageReady: true,
      slots: ["section-header", "cards", "media"],
      variants: [
        v("team-grid", "Team grid", "card-grid", "editorial",
          `figure{margin:0}img{aspect-ratio:1;object-fit:cover;border-radius:var(--r);width:100%}figcaption{margin-top:10px}span{display:block;color:var(--muted)}`,
          `<section class="block"><div class="w"><p class="ey">People</p><h2>The studio</h2><div class="g3" style="margin-top:20px"><figure>${img(4, "Portrait of Ada Loren, principal")}<figcaption><strong>Ada Loren</strong><span>Principal</span></figcaption></figure><figure>${img(5, "Portrait of Miles Chen at the bench")}<figcaption><strong>Miles Chen</strong><span>Maker</span></figcaption></figure><figure>${img(8, "Portrait of Noor Hale during service")}<figcaption><strong>Noor Hale</strong><span>Producer</span></figcaption></figure></div></div></section>`),
        v("team-list", "Team list", "stack", "studio",
          `article{display:grid;grid-template-columns:88px 1fr;gap:14px;align-items:center;padding:12px 0;border-bottom:1px solid var(--line)}img{width:88px;height:88px;object-fit:cover;border-radius:50%}`,
          `<section class="block"><div class="w" style="max-width:680px"><h2>Who you will meet</h2><article>${img(4, "Ada Loren")}<div><h3>Ada Loren</h3><p class="lede">Leads the brief and the drawings.</p></div></article><article>${img(5, "Miles Chen")}<div><h3>Miles Chen</h3><p class="lede">Runs the shop and the install.</p></div></article></div></section>`),
        v("team-featured", "Featured team member", "split-media", "soft",
          `.feat{align-items:center}img{border-radius:var(--r);width:100%;aspect-ratio:4/5;object-fit:cover}`,
          `<section class="block"><div class="w g2 feat">${img(4, "Ada Loren in the studio")}<div><p class="ey">Principal</p><h2>Ada Loren</h2><p class="lede">Ada started Northline after a decade of residential work. She still draws every plan.</p></div></div></section>`),
        v("team-compact", "Compact team row", "flex-row", "sharp",
          `.row{display:flex;gap:18px;flex-wrap:wrap;margin-top:16px}figure{margin:0;width:140px}img{width:140px;height:160px;object-fit:cover}`,
          `<section class="block"><div class="w"><h2>Team</h2><div class="row"><figure>${img(4, "Ada Loren")}<figcaption>Ada Loren</figcaption></figure><figure>${img(5, "Miles Chen")}<figcaption>Miles Chen</figcaption></figure><figure>${img(8, "Noor Hale")}<figcaption>Noor Hale</figcaption></figure></div></div></section>`),
      ],
    },
    {
      category: "bios",
      role: "team",
      pageReady: true,
      slots: ["section-header", "cards", "media"],
      variants: [
        v("bio-card", "Biography card", "split-media", "editorial",
          `article{display:grid;grid-template-columns:200px 1fr;gap:20px;background:var(--surface);padding:16px;border-radius:var(--r)}img{width:200px;height:240px;object-fit:cover;border-radius:10px}@media(max-width:800px){article{grid-template-columns:1fr}img{width:100%}}`,
          `<section class="block"><div class="w"><article>${img(4, "Portrait of Ada Loren")}<div><p class="ey">Bio</p><h2>Ada Loren</h2><p class="lede">Principal. Trained in interiors, happiest on a job site with a pencil.</p></div></article></div></section>`),
        v("bio-list", "Short biographies", "stack", "studio",
          `article{padding:18px 0;border-top:1px solid var(--line)}`,
          `<section class="block"><div class="w"><article><h3>Miles Chen</h3><p class="lede">Leads fabrication and teaches the crew the finish standard.</p></article><article><h3>Noor Hale</h3><p class="lede">Keeps schedules honest and clients informed.</p></article></div></section>`),
        v("bio-quote", "Biography with quote", "centered", "soft",
          `figure{max-width:40rem;margin:0}blockquote{font-family:var(--d);font-size:1.8rem;line-height:1.2;margin:0 0 12px}`,
          `<section class="block"><div class="w"><figure><blockquote>“Draw it so a stranger could build it.”</blockquote><figcaption class="lede">Ada Loren, on the office wall</figcaption></figure></div></section>`),
        v("bio-meta", "Biography with role", "flex-row", "sharp",
          `.row{display:flex;gap:16px;align-items:center}img{width:96px;height:96px;object-fit:cover}`,
          `<section class="block"><div class="w row">${img(5, "Miles Chen")}<div><p class="ey">Maker</p><h2>Miles Chen</h2><p class="lede">Shop lead since 2019.</p></div></div></section>`),
      ],
    },
    {
      category: "text-sections",
      role: "about",
      pageReady: true,
      slots: ["section-header", "body-copy", "media"],
      variants: [
        v("prose-section", "Narrow prose", "stack", "editorial",
          `.prose{max-width:40rem}.prose p{margin-top:14px;font-size:1.05rem}`,
          `<section class="block"><div class="w prose"><p class="ey">About</p><h2>A studio of eight.</h2><p>Northline started as a one-room practice and stayed small on purpose. We take fewer jobs so the people who draw them can still be on site.</p><p>Most work is residential. A few shops each year keep the details sharp.</p></div></section>`),
        v("two-column-text", "Two-column text", "multi-column", "studio",
          `.cols{column-count:2;column-gap:32px;margin-top:16px}@media(max-width:800px){.cols{column-count:1}}`,
          `<section class="block"><div class="w"><h2>Why we stay small</h2><div class="cols"><p>A large office can hide a weak detail. We would rather know every hinge. Clients meet the person who will run their job, not a handoff.</p><p>The studio is on Harbor Ave. Samples live on the wall. If a finish is here, we have used it.</p></div></div></section>`),
        v("media-text", "Text with image", "split-media", "soft",
          `.row{align-items:center}img{border-radius:var(--r);width:100%;aspect-ratio:5/4;object-fit:cover}p{margin-top:12px}`,
          `<section class="block"><div class="w g2 row">${img(0, "Studio living room sample")}<div><p class="ey">Practice</p><h2>We design what we can stand behind.</h2><p class="lede">Materials are chosen for repair, not for a photograph.</p></div></div></section>`),
        v("pull-text", "Text with pull line", "stack", "sharp",
          `.pull{font-family:var(--d);font-size:clamp(1.8rem,3vw,2.4rem);line-height:1.15;max-width:18ch;margin-top:16px}`,
          `<section class="block"><div class="w"><p class="ey">Note</p><p class="pull">The best rooms are the ones you stop photographing.</p><p class="lede" style="margin-top:14px">That is the standard we use in reviews.</p></div></section>`),
      ],
    },
    {
      category: "rich-text",
      role: "about",
      pageReady: true,
      slots: ["section-header", "body-copy"],
      variants: [
        v("article-rich", "Article rich text", "stack", "editorial",
          `article{max-width:42rem}h2{margin:22px 0 8px;font-size:1.6rem}p{margin:0 0 12px}`,
          `<article class="w block"><p class="ey">Journal</p><h1 style="font-size:clamp(2rem,4vw,3rem)">Limewash, after a year</h1><p class="lede">What actually changes on a north wall.</p><h2>The first month</h2><p>Color settles. The cloudy patches were always in the plaster, not the paint.</p><h2>The repair</h2><p>A damp sponge and the same mix. No full repaint.</p></article>`),
        v("dropcap-rich", "Drop cap text", "stack", "soft",
          `.drop::first-letter{font-family:var(--d);float:left;font-size:3.2rem;line-height:.8;padding-right:8px}article{max-width:40rem}`,
          `<article class="w block"><h2>On samples</h2><p class="drop">Bring them home. A chip in the studio is a guess. Live with it beside the window you actually have.</p></article>`),
        v("quote-rich", "Rich text with quote", "stack", "studio",
          `blockquote{margin:16px 0;padding-left:16px;border-left:2px solid var(--line);font-family:var(--d);font-size:1.5rem}article{max-width:40rem}`,
          `<article class="w block"><h2>From the bench</h2><p>We keep a board of rejected finishes.</p><blockquote>If it only looks right in the photo, it does not ship.</blockquote><p class="lede">Miles writes that on the sample tags.</p></article>`),
        v("scale-rich", "Heading scale", "stack", "sharp",
          `article{max-width:46rem}h2{font-size:1.4rem;margin-top:18px}h3{font-size:1.05rem;letter-spacing:.08em;text-transform:uppercase;margin-top:14px}`,
          `<article class="w block"><h1 style="font-size:2.4rem">Field guide</h1><h2>Light</h2><p>Measure it at 4pm, not at noon.</p><h3>Hardware</h3><p>Unlacquered brass if someone will touch it. Otherwise powder coat.</p></article>`),
      ],
    },
    {
      category: "sections",
      role: "about",
      pageReady: true,
      slots: ["section-header", "body-copy", "media"],
      variants: [
        v("contained-section", "Contained section", "stack", "editorial",
          `.panel{background:var(--surface);border-radius:var(--r);padding:32px;box-shadow:var(--sh)}`,
          `<section class="block"><div class="w panel"><p class="ey">Note</p><h2>We publish the number before we start.</h2><p class="lede">Allowances are written in the proposal, not discovered later.</p></div></section>`),
        v("full-bleed-section", "Full-bleed band", "band", "studio",
          `.band{padding:72px 0;background:var(--surface)}`,
          `<section class="band"><div class="w"><p class="ey">Standard</p><h2>One job, fully staffed.</h2><p class="lede">We do not split a crew across three sites.</p></div></section>`),
        v("two-column-section", "Two-column section", "multi-column", "soft",
          ``,
          `<section class="block"><div class="w g2"><div><h2>For homes</h2><p class="lede">Kitchens, stairs, and the rooms you use every day.</p></div><div><h2>For shops</h2><p class="lede">Fixtures, lighting, and a floor that can be cleaned.</p></div></div></section>`),
        v("accent-section", "Accent band section", "band", "sharp",
          `.band{background:var(--ink);color:var(--on);padding:56px 0}`,
          `<section class="band"><div class="w"><h2>Currently booking June.</h2><p>Write if your date is sooner. We will say so if we cannot.</p></div></section>`),
      ],
    },
    {
      category: "announcements",
      role: "credibility",
      pageReady: true,
      slots: ["headline", "cta"],
      variants: [
        v("top-announcement", "Top announcement bar", "band", "editorial",
          `.bar{background:var(--ink);color:var(--on);padding:10px 16px;display:flex;justify-content:center;gap:12px;flex-wrap:wrap;text-align:center}.bar a{text-decoration:underline;min-height:44px;display:inline-flex;align-items:center}`,
          `<div class="bar"><span>Studio hours change next week.</span><a href="#visit">See the new hours</a></div>`),
        v("inline-announcement", "Inline announcement", "band", "studio",
          `.note{margin:16px auto;padding:14px 16px;border:1px solid var(--line);border-radius:var(--r);display:flex;justify-content:space-between;gap:12px;align-items:center;width:min(var(--max),calc(100% - 40px))}@media(max-width:800px){.note{flex-direction:column;align-items:flex-start}}`,
          `<p class="note"><span>We are on site Thursdays and not at the desk.</span><a class="btn" href="#visit">Leave a note</a></p>`),
        v("dismiss-announcement", "Dismissible announcement", "band", "soft",
          `.bar{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:12px 16px;background:var(--surface);border-bottom:1px solid var(--line)}button{width:48px;height:48px;border:0;background:transparent}`,
          `<div class="bar" id="ann"><p>Sample library is open Saturday until 2.</p><button type="button" aria-label="Dismiss announcement" onclick="document.getElementById('ann').remove()">${I.close}</button></div>`),
        v("pill-announcement", "Status announcement", "centered", "sharp",
          `.pill{display:inline-flex;gap:8px;align-items:center;border:1px solid var(--line);padding:8px 12px;border-radius:var(--r);margin:16px}`,
          `<p class="pill"><span aria-hidden="true" style="width:8px;height:8px;border-radius:50%;background:#2f7d4a;display:inline-block"></span> Booking June projects now</p>`),
      ],
    },
    {
      category: "logos",
      role: "credibility",
      pageReady: true,
      slots: ["section-header", "proof-items"],
      variants: [
        v("logo-strip", "Logo strip", "flex-row", "editorial",
          `.row{display:flex;flex-wrap:wrap;gap:18px 28px;align-items:center;margin-top:16px}.mark{font-weight:750;letter-spacing:.08em;text-transform:uppercase;color:var(--muted);min-height:44px;display:inline-flex;align-items:center}`,
          `<section class="block"><div class="w"><p class="ey">Seen with</p><div class="row"><span class="mark">Harbor & Co</span><span class="mark">Field Day</span><span class="mark">Atelier 9</span><span class="mark">Kindred</span><span class="mark">Oak Supply</span></div></div></section>`),
        v("logo-grid", "Logo grid", "card-grid", "studio",
          `.cell{border:1px solid var(--line);min-height:88px;display:grid;place-items:center;font-weight:700;letter-spacing:.06em;text-transform:uppercase;color:var(--muted)}`,
          `<section class="block"><div class="w g3"><div class="cell">Harbor</div><div class="cell">Field Day</div><div class="cell">Kindred</div><div class="cell">Oak</div><div class="cell">Lumen</div><div class="cell">Marrow</div></div></section>`),
        v("logo-marquee", "Logo row with caption", "marquee", "soft",
          `.row{display:flex;gap:28px;overflow:auto;padding:8px 0;margin-top:10px}.mark{flex:none;font-family:var(--d);font-size:1.4rem;color:var(--muted)}`,
          `<section class="block"><div class="w"><p class="ey">Collaborators</p><div class="row" tabindex="0"><span class="mark">Harbor & Co</span><span class="mark">Field Day</span><span class="mark">Atelier 9</span><span class="mark">Kindred Market</span></div></div></section>`),
        v("logo-caption", "Captioned clients", "stack", "sharp",
          `.row{display:flex;justify-content:space-between;gap:12px;padding:12px 0;border-bottom:1px solid var(--line)}`,
          `<section class="block"><div class="w"><h2>Selected clients</h2><div class="row"><strong>Harbor & Co</strong><span class="lede">Shop</span></div><div class="row"><strong>Field Day</strong><span class="lede">Cafe</span></div><div class="row"><strong>Kindred</strong><span class="lede">Home</span></div></div></section>`),
      ],
    },
    {
      category: "stats",
      role: "credibility",
      pageReady: true,
      slots: ["section-header", "proof-items"],
      variants: [
        v("stat-row", "Stat row", "flex-row", "editorial",
          `.row{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin-top:12px}.n{font-family:var(--d);font-size:clamp(2rem,4vw,3rem)}@media(max-width:800px){.row{grid-template-columns:1fr}}`,
          `<section class="block"><div class="w row"><div><p class="n">12</p><p class="lede">years of the practice</p></div><div><p class="n">8</p><p class="lede">people in the studio</p></div><div><p class="n">1</p><p class="lede">crew on your job</p></div></div></section>`),
        v("stat-cards", "Stat cards", "card-grid", "studio",
          `article{background:var(--surface);border:1px solid var(--line);border-radius:var(--r);padding:18px}.n{font-family:var(--d);font-size:2.4rem}`,
          `<section class="block"><div class="w g3"><article><p class="n">48</p><p class="lede">rooms this year</p></article><article><p class="n">4</p><p class="lede">week typical design</p></article><article><p class="n">2</p><p class="lede">revision rounds included</p></article></div></section>`),
        v("stat-split", "Split statistic", "split-media", "soft",
          `.n{font-family:var(--d);font-size:clamp(3rem,8vw,6rem);line-height:.9}`,
          `<section class="block"><div class="w g2" style="align-items:end"><p class="n">2014</p><div><h2>Founded on Harbor Ave.</h2><p class="lede">Still in the same room.</p></div></div></section>`),
        v("stat-list", "Labeled figures", "numbered-list", "sharp",
          `.row{display:grid;grid-template-columns:120px 1fr;gap:12px;padding:12px 0;border-top:1px solid var(--line)}`,
          `<section class="block"><div class="w" style="max-width:640px"><div class="row"><strong>90 min</strong><span>Typical first visit</span></div><div class="row"><strong>1 day</strong><span>To send the notes</span></div><div class="row"><strong>0</strong><span>Surprise allowances</span></div></div></section>`),
      ],
    },
    {
      category: "quotes",
      role: "testimonials",
      pageReady: true,
      slots: ["proof-items"],
      variants: [
        v("pull-quote", "Pull quote", "centered", "editorial",
          `blockquote{font-family:var(--d);font-size:clamp(1.8rem,4vw,2.8rem);line-height:1.15;max-width:16em;margin:0}`,
          `<section class="block"><div class="w"><blockquote>“Leave the wall a little imperfect. That is the point.”</blockquote><p class="lede" style="margin-top:12px">From the finish notes</p></div></section>`),
        v("cite-quote", "Cited quote", "stack", "studio",
          `figure{margin:0;max-width:36rem}blockquote{margin:0 0 10px;font-size:1.4rem}`,
          `<section class="block"><div class="w"><figure><blockquote>The budget on page one matched the invoice.</blockquote><figcaption class="lede">— Client, market project</figcaption></figure></div></section>`),
        v("band-quote", "Quote band", "band", "soft",
          `.band{background:var(--surface);padding:48px 0;border-top:1px solid var(--line);border-bottom:1px solid var(--line)}blockquote{font-family:var(--d);font-size:1.8rem;margin:0}`,
          `<section class="band"><div class="w"><blockquote>Come Thursday. The light is honest then.</blockquote></div></section>`),
        v("aside-quote", "Aside quote", "split-media", "sharp",
          `.q{border-left:2px solid var(--ink);padding-left:16px;font-family:var(--d);font-size:1.6rem;line-height:1.2}`,
          `<section class="block"><div class="w g2"><p class="q">Specify less. Specify it twice.</p><p class="lede">A line we keep on the drawing set.</p></div></section>`),
      ],
    },
    {
      category: "comparisons",
      role: "pricing",
      pageReady: true,
      slots: ["section-header", "cards"],
      variants: [
        v("compare-table", "Comparison table", "multi-column", "editorial",
          `table{width:100%;border-collapse:collapse;margin-top:16px}th,td{padding:12px;border-bottom:1px solid var(--line);text-align:left}th{font-weight:650}`,
          `<section class="block"><div class="w" style="overflow:auto"><h2>Choose a start</h2><table><thead><tr><th scope="col">Includes</th><th scope="col">Consult</th><th scope="col">Design</th></tr></thead><tbody><tr><th scope="row">Site visit</th><td>Yes</td><td>Yes</td></tr><tr><th scope="row">Drawings</th><td>—</td><td>Yes</td></tr><tr><th scope="row">Budget</th><td>Range</td><td>Itemized</td></tr></tbody></table></div></section>`),
        v("compare-cards", "Comparison cards", "card-grid", "studio",
          `article{border:1px solid var(--line);border-radius:var(--r);padding:18px;background:var(--surface)}li{margin:6px 0 6px 18px;color:var(--muted)}`,
          `<section class="block"><div class="w g2"><article><h3>Advice</h3><ul><li>One visit</li><li>Priority list</li></ul></article><article><h3>Full service</h3><ul><li>Drawings</li><li>Crew</li><li>Walkthrough</li></ul></article></div></section>`),
        v("compare-checks", "Check grid", "card-grid", "soft",
          `.yes{color:var(--ink);font-weight:700}table{width:100%;border-collapse:collapse}td,th{padding:10px;border-bottom:1px solid var(--line);text-align:left}`,
          `<section class="block"><div class="w" style="overflow:auto"><table><thead><tr><th scope="col">Item</th><th scope="col">Us</th><th scope="col">Typical</th></tr></thead><tbody><tr><th scope="row">Named lead</th><td class="yes">Included</td><td>Varies</td></tr><tr><th scope="row">Written number</th><td class="yes">Before start</td><td>After demo</td></tr></tbody></table></div></section>`),
        v("compare-split", "Split comparison", "split-media", "sharp",
          `article{padding:8px 0 8px 16px;border-left:2px solid var(--line)}`,
          `<section class="block"><div class="w g2"><article><p class="ey">With a plan</p><h3>Fewer change orders</h3><p class="lede">Decisions happen on paper.</p></article><article><p class="ey">Without</p><h3>The job site decides</h3><p class="lede">Usually the expensive way.</p></article></div></section>`),
      ],
    },
    {
      category: "videos",
      role: "hero",
      pageReady: true,
      slots: ["headline", "media", "cta"],
      variants: [
        v("background-video", "Background video hero", "split-media", "editorial",
          `.hero{position:relative;min-height:100svh;display:grid;align-items:end;color:#fff}.hero video,.hero img{position:absolute;inset:0;width:100%;height:100%;object-fit:cover}.shade{position:absolute;inset:0;background:rgba(0,0,0,.4)}.copy{position:relative;padding-bottom:48px}`,
          `<section class="hero"><video autoplay muted loop playsinline poster="https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1600&q=80"><source src="https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4" type="video/mp4"></video><div class="shade"></div><div class="w copy"><h1>Watch the light move.</h1><a class="btn" href="#work" style="margin-top:12px">See projects</a></div></section>`),
        v("inline-video", "Inline video", "stack", "studio",
          `figure{margin:0}video{width:100%;border-radius:var(--r);background:#000}figcaption{margin-top:8px}`,
          `<section class="block"><div class="w"><figure><video controls playsinline preload="metadata" poster="https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=1600&q=80"><source src="https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4" type="video/mp4"></video><figcaption class="lede">A short walk through the stair.</figcaption></figure></div></section>`),
        v("poster-video", "Poster video", "split-media", "soft",
          `.row{align-items:center}video{width:100%;border-radius:var(--r)}`,
          `<section class="block"><div class="w g2 row"><video controls playsinline poster="https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=1200&q=80"><source src="https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4" type="video/mp4"></video><div><p class="ey">Film</p><h2>Two minutes on site.</h2><p class="lede">No music. Just the room.</p></div></div></section>`),
        v("captioned-video", "Captioned video", "stack", "sharp",
          `video{width:100%;max-height:70svh;background:#111}`,
          `<section class="block"><div class="w"><h2>Process film</h2><video controls playsinline preload="metadata" aria-describedby="vcap" poster="https://images.unsplash.com/photo-1452860606245-08befc0ff44b?auto=format&fit=crop&w=1400&q=80"><source src="https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4" type="video/mp4"></video><p id="vcap" class="lede" style="margin-top:8px">Captions available in the player. Silent cut of the install week.</p></div></section>`),
      ],
    },
    {
      category: "images",
      role: "gallery",
      pageReady: true,
      slots: ["media", "section-header"],
      variants: [
        v("framed-image", "Framed image", "stack", "editorial",
          `figure{margin:0}img{border-radius:var(--r);width:100%}figcaption{margin-top:8px}`,
          `<section class="block"><div class="w"><figure>${img(1, "House exterior in afternoon light")}<figcaption class="lede">Hill house, west elevation.</figcaption></figure></div></section>`),
        v("duo-images", "Two images", "card-grid", "studio",
          `.duo img{width:100%;aspect-ratio:4/5;object-fit:cover;border-radius:var(--r)}`,
          `<section class="block"><div class="w g2 duo">${img(0, "Living room")}${img(7, "Work table")}</div></section>`),
        v("caption-image", "Image with long caption", "split-media", "soft",
          `figure{display:grid;grid-template-columns:1.4fr .8fr;gap:18px;align-items:end;margin:0}@media(max-width:800px){figure{grid-template-columns:1fr}}img{border-radius:var(--r)}`,
          `<section class="block"><div class="w"><figure>${img(3, "Counter and cups")}<figcaption><p class="ey">Detail</p><p>The counter is white oak, oiled, not filmed. It will mark. That is the agreement.</p></figcaption></figure></div></section>`),
        v("bleed-image", "Full-bleed image", "band", "sharp",
          `figure{margin:0}img{width:100%;max-height:80svh;object-fit:cover}`,
          `<figure>${img(9, "Open sky over a low landscape")}</figure>`),
      ],
    },
    {
      category: "carousels",
      role: "gallery",
      pageReady: true,
      slots: ["media", "section-header"],
      variants: [
        v("snap-carousel", "Snap carousel", "marquee", "editorial",
          `.sc{display:flex;gap:12px;overflow:auto;scroll-snap-type:x mandatory;margin-top:16px}.sc figure{margin:0;flex:none;width:min(78vw,460px);scroll-snap-align:start}.sc img{width:100%;height:300px;object-fit:cover;border-radius:var(--r)}.ctrls{display:flex;gap:8px;margin-top:12px}button{width:48px;height:48px;border-radius:var(--r);border:1px solid var(--line);background:var(--surface)}`,
          `<section class="block" data-car><div class="w"><h2>Rooms</h2><div class="sc" data-scroller tabindex="0">${[0, 1, 3, 6].map((i) => `<figure>${img(i, "Project photo")}</figure>`).join("")}</div><div class="ctrls"><button type="button" data-prev aria-label="Previous">${I.arrow}</button><button type="button" data-next aria-label="Next" style="transform:scaleX(-1)">${I.arrow}</button></div></div></section>`,
          JS.car),
        v("peek-carousel", "Peek carousel", "marquee", "studio",
          `.sc{display:grid;grid-auto-flow:column;grid-auto-columns:70%;gap:12px;overflow:auto}img{height:240px;width:100%;object-fit:cover;border-radius:12px}`,
          `<section class="block"><div class="w sc" tabindex="0">${img(2, "Workshop")}${img(5, "Hands")}${img(8, "Table")}</div></section>`),
        v("quote-carousel", "Quote carousel", "card-grid", "soft",
          `.sc{display:flex;gap:12px;overflow:auto}blockquote{flex:none;width:min(80vw,420px);background:var(--surface);border-radius:var(--r);padding:18px;margin:0;font-family:var(--d);font-size:1.3rem}`,
          `<section class="block"><div class="w sc" tabindex="0" aria-label="Quotes"><blockquote>“Calmer than they found it.”<span class="lede" style="display:block;margin-top:8px">Mara E.</span></blockquote><blockquote>“Opened on the day they named.”<span class="lede" style="display:block;margin-top:8px">Jon P.</span></blockquote></div></section>`),
        v("controlled-carousel", "Carousel with count", "marquee", "sharp",
          `.sc{display:flex;gap:8px;overflow:auto}img{width:280px;height:180px;object-fit:cover;flex:none}`,
          `<section class="block" data-car><div class="w"><p class="ey">4 photos</p><div class="sc" data-scroller>${img(0, "One")}${img(1, "Two")}${img(7, "Three")}${img(6, "Four")}</div><button class="btn gh" type="button" data-next style="margin-top:12px">Next</button></div></section>`,
          JS.car),
      ],
    },
  ];

  const videos = groups.find((group) => group.category === "videos");
  for (const variant of videos.variants) {
    if (variant.slug !== "background-video") {
      variant.pageReady = false;
      variant.role = "gallery";
    }
  }
  return groups;
};
