"use strict";

module.exports = function controls({ img, I, JS }) {
  const v = (slug, title, layout, family, css, html, js = "") => ({ slug, title, layout, family, css, html, js });
  const atom = (category, slots, variants) => ({ category, role: "ornament", pageReady: false, slots, variants });

  return [
    atom("buttons", ["cta"], [
      v("solid-buttons", "Solid and ghost buttons", "flex-row", "editorial",
        `.row{display:flex;flex-wrap:wrap;gap:12px;padding:48px 20px}`,
        `<div class="row"><button class="btn" type="button">Book a visit</button><button class="btn gh" type="button">See the work</button><button class="btn" type="button" disabled>Unavailable</button></div>`),
      v("icon-buttons", "Icon buttons", "flex-row", "studio",
        `.row{display:flex;gap:12px;padding:48px 20px;flex-wrap:wrap}.sq{width:48px;height:48px;padding:0}`,
        `<div class="row"><button class="btn" type="button">Continue ${I.arrow}</button><button class="btn sq" type="button" aria-label="Search">${I.search}</button><button class="btn gh sq" type="button" aria-label="Close">${I.close}</button></div>`),
      v("button-group", "Button group", "flex-row", "soft",
        `.grp{display:inline-flex;padding:48px 20px}.grp .btn{border-radius:0}.grp .btn:first-child{border-radius:var(--r) 0 0 var(--r)}.grp .btn:last-child{border-radius:0 var(--r) var(--r) 0}`,
        `<div class="grp" role="group" aria-label="View"><button class="btn" type="button" aria-pressed="true">List</button><button class="btn gh" type="button" aria-pressed="false">Grid</button></div>`),
      v("full-buttons", "Full-width buttons", "stack", "sharp",
        `.stack{display:grid;gap:10px;max-width:360px;padding:32px 20px}.btn{width:100%}`,
        `<div class="stack"><button class="btn" type="button">Confirm</button><button class="btn gh" type="button">Cancel</button></div>`),
    ]),
    atom("inputs", ["form-fields"], [
      v("boxed-input", "Boxed input", "form-stack", "editorial",
        `.box{max-width:420px;padding:32px 20px;display:grid;gap:8px}`,
        `<div class="box"><label class="fld">Email<input type="email" name="email" autocomplete="email" placeholder="you@studio.com"></label><p class="hint">We reply to this address.</p></div>`),
      v("icon-input", "Icon input", "form-stack", "studio",
        `.box{max-width:440px;padding:32px 20px}.wrap{position:relative}.wrap svg{position:absolute;left:12px;top:14px}.wrap input{padding-left:40px}`,
        `<div class="box"><label class="fld">Search the journal<span class="wrap">${I.search}<input type="search" placeholder="Stairs, oak, limewash"></span></label></div>`),
      v("validated-input", "Validated input", "form-stack", "soft",
        `.box{max-width:420px;padding:32px 20px}.bad{border-color:#8f2d2d!important}.err{color:#8f2d2d;font-size:.85rem}`,
        `<div class="box"><label class="fld">Phone<input class="bad" aria-invalid="true" aria-describedby="e1" value="555"><span id="e1" class="err">Enter a full number, including area code.</span></label></div>`),
      v("password-input", "Password input", "form-stack", "sharp",
        `.box{max-width:420px;padding:32px 20px}.row{display:flex;justify-content:space-between;align-items:center}button{background:none;border:0;min-height:44px;font-weight:650}`,
        `<div class="box"><label class="fld"><span class="row">Password <button type="button" onclick="const i=document.getElementById('pw');i.type=i.type==='password'?'text':'password'">Show</button></span><input id="pw" type="password" autocomplete="current-password"></label></div>`),
    ]),
    atom("textareas", ["form-fields"], [
      v("plain-textarea", "Plain textarea", "form-stack", "editorial",
        `.box{max-width:520px;padding:32px 20px}`,
        `<div class="box"><label class="fld">Project notes<textarea placeholder="Room, timeline, neighborhood"></textarea></label></div>`),
      v("counter-textarea", "Textarea with counter", "form-stack", "studio",
        `.box{max-width:520px;padding:32px 20px}.row{display:flex;justify-content:space-between}`,
        `<div class="box"><label class="fld"><span class="row">Note <span class="hint" id="c">0 / 240</span></span><textarea maxlength="240" oninput="document.getElementById('c').textContent=this.value.length+' / 240'"></textarea></label></div>`),
      v("minimal-textarea", "Minimal textarea", "form-stack", "soft",
        `textarea{width:min(520px,calc(100% - 40px));margin:32px 20px;border:0;border-bottom:1px solid var(--line);border-radius:0;background:transparent;min-height:120px}`,
        `<label class="fld" style="padding:20px">Letter<textarea placeholder="Write it plainly."></textarea></label>`),
      v("toolbar-textarea", "Textarea with toolbar", "form-stack", "sharp",
        `.box{max-width:560px;margin:24px auto;border:1px solid var(--line);background:var(--surface)}.tools{display:flex;gap:4px;padding:6px;border-bottom:1px solid var(--line)}button{min-width:44px;min-height:44px;border:0;background:transparent;font-weight:700}textarea{border:0;width:100%}`,
        `<div class="box"><div class="tools" aria-hidden="true"><button type="button">B</button><button type="button">I</button></div><label class="fld">Body<textarea></textarea></label></div>`),
    ]),
    atom("selects", ["form-fields"], [
      v("native-select", "Native select", "form-stack", "editorial",
        `.box{max-width:360px;padding:32px 20px}`,
        `<div class="box"><label class="fld">Room<select><option>Kitchen</option><option>Stair</option><option>Shop</option></select></label></div>`),
      v("custom-select", "Custom select menu", "form-stack", "studio",
        `.box{max-width:320px;padding:32px 20px;position:relative}button.btn{width:100%;justify-content:space-between}ul{list-style:none;margin:6px 0 0;padding:6px;background:var(--surface);border:1px solid var(--line);border-radius:var(--r)}li button{width:100%;text-align:left;background:none;border:0;min-height:44px}`,
        `<div class="box" data-drop><button class="btn gh" type="button" aria-expanded="false" aria-haspopup="listbox">Choose a service ${I.chev}</button><ul data-menu hidden role="listbox"><li><button type="button" role="option">Consult</button></li><li><button type="button" role="option">Design</button></li></ul></div>`,
        JS.drop),
      v("multi-select", "Checkbox multi-select", "form-stack", "soft",
        `.box{max-width:360px;padding:24px 20px}label{display:flex;gap:10px;align-items:center;min-height:44px}`,
        `<fieldset class="box"><legend class="ey">Rooms</legend><label><input type="checkbox" checked> Kitchen</label><label><input type="checkbox"> Bath</label><label><input type="checkbox"> Stair</label></fieldset>`),
      v("search-select", "Searchable list", "form-stack", "sharp",
        `.box{max-width:360px;padding:24px 20px}ul{list-style:none;margin:8px 0 0;padding:0}li{padding:10px 0;border-bottom:1px solid var(--line)}`,
        `<div class="box"><label class="fld">Find a finish<input type="search" placeholder="Oak, lime, brass"></label><ul><li>White oak</li><li>Limewash</li><li>Unlacquered brass</li></ul></div>`),
    ]),
    atom("checkboxes", ["form-fields"], [
      v("check-list", "Checkbox list", "stack", "editorial",
        `label{display:flex;gap:10px;align-items:center;min-height:44px;max-width:360px;margin:0 20px}`,
        `<fieldset style="border:0;padding:24px 0"><legend class="w ey">Include</legend><label><input type="checkbox" checked> Drawings</label><label><input type="checkbox"> Samples</label><label><input type="checkbox"> Site visits</label></fieldset>`),
      v("check-cards", "Checkbox cards", "card-grid", "studio",
        `.opt{display:grid;grid-template-columns:1fr 1fr;gap:10px;max-width:520px;padding:24px}label{border:1px solid var(--line);border-radius:var(--r);padding:12px;min-height:72px;display:flex;gap:8px;align-items:flex-start;background:var(--surface)}`,
        `<div class="opt"><label><input type="checkbox" checked> Morning visit</label><label><input type="checkbox"> Afternoon visit</label></div>`),
      v("check-mixed", "Indeterminate checkbox", "stack", "soft",
        `label{display:flex;gap:10px;align-items:center;min-height:48px;padding:20px}`,
        `<label><input type="checkbox" id="all"> Select visible notes</label><script>document.getElementById("all").indeterminate=true</script>`),
      v("check-desc", "Checkbox with description", "stack", "sharp",
        `label{display:grid;grid-template-columns:24px 1fr;gap:8px 10px;max-width:460px;padding:24px;align-items:start}small{grid-column:2;color:var(--muted)}`,
        `<label><input type="checkbox"><span>Send the sample set</span><small>We ship three finishes, not the whole library.</small></label>`),
    ]),
    atom("radios", ["form-fields"], [
      v("radio-list", "Radio list", "stack", "editorial",
        `label{display:flex;gap:10px;align-items:center;min-height:44px}`,
        `<fieldset style="border:0;padding:24px 20px"><legend class="ey">Timing</legend><label><input type="radio" name="t" checked> This month</label><label><input type="radio" name="t"> This season</label><label><input type="radio" name="t"> Just looking</label></fieldset>`),
      v("radio-cards", "Radio cards", "card-grid", "studio",
        `.g{display:grid;gap:8px;max-width:420px;padding:24px}label{border:1px solid var(--line);border-radius:var(--r);padding:12px;display:flex;gap:8px;background:var(--surface)}`,
        `<div class="g" role="radiogroup" aria-label="Plan"><label><input type="radio" name="p" checked> Consult</label><label><input type="radio" name="p"> Design</label></div>`),
      v("radio-segment", "Segmented radio", "flex-row", "soft",
        `.seg{display:inline-flex;padding:24px;border:1px solid var(--line);border-radius:var(--r);overflow:hidden}label{min-height:48px;padding:0 14px;display:inline-flex;align-items:center}input{position:absolute;opacity:0}input:checked+span{font-weight:750}input:focus-visible+span{outline:2px solid var(--accent)}`,
        `<div class="seg" role="radiogroup" aria-label="Units"><label><input type="radio" name="u" checked><span>Feet</span></label><label><input type="radio" name="u"><span>Meters</span></label></div>`),
      v("radio-desc", "Radio with help", "stack", "sharp",
        `label{display:grid;grid-template-columns:24px 1fr;gap:4px 8px;max-width:460px;margin:12px 20px}small{color:var(--muted)}`,
        `<fieldset style="border:0"><legend class="w">Start</legend><label><input type="radio" name="s" checked><span>Advice</span><small>One visit and notes.</small></label><label><input type="radio" name="s"><span>Drawings</span><small>A set you can price.</small></label></fieldset>`),
    ]),
    atom("toggles", ["form-fields"], [
      v("switch-toggle", "Switch", "flex-row", "editorial",
        `.sw{display:flex;align-items:center;justify-content:space-between;gap:12px;max-width:360px;padding:24px 20px}input{width:48px;height:28px;accent-color:var(--accent)}`,
        `<label class="sw"><span>Email the notes</span><input type="checkbox" role="switch" checked></label>`),
      v("labeled-toggles", "Labeled switches", "stack", "studio",
        `.row{display:flex;justify-content:space-between;align-items:center;max-width:420px;padding:12px 20px;border-bottom:1px solid var(--line)}`,
        `<div><div class="row"><span>Public profile</span><input type="checkbox" role="switch"></div><div class="row"><span>Weekly digest</span><input type="checkbox" role="switch" checked></div></div>`),
      v("card-toggle", "Card switch", "card-grid", "soft",
        `label{display:flex;justify-content:space-between;gap:12px;align-items:center;max-width:460px;margin:24px;padding:16px;background:var(--surface);border-radius:var(--r);border:1px solid var(--line)}`,
        `<label><span><strong>Install updates</strong><br><span class="lede">A text when the crew is on the way.</span></span><input type="checkbox" role="switch" checked></label>`),
      v("pill-toggle", "Choice toggle", "flex-row", "sharp",
        `.seg{display:inline-flex;margin:24px;border:1px solid var(--line)}button{min-height:48px;padding:0 16px;border:0;background:transparent}button[aria-pressed=true]{background:var(--ink);color:var(--on)}`,
        `<div class="seg" role="group" aria-label="Theme"><button type="button" aria-pressed="true">Light</button><button type="button" aria-pressed="false" onclick="this.setAttribute('aria-pressed','true');this.previousElementSibling.setAttribute('aria-pressed','false')">Dark</button></div>`),
    ]),
    atom("sliders", ["form-fields"], [
      v("range-slider", "Range slider", "stack", "editorial",
        `.box{max-width:420px;padding:32px 20px}input{width:100%;accent-color:var(--accent);height:28px}`,
        `<label class="box fld">Budget ceiling<strong id="b">$12,000</strong><input type="range" min="2000" max="40000" value="12000" step="500" oninput="document.getElementById('b').textContent='$'+Number(this.value).toLocaleString()"></label>`),
      v("step-slider", "Stepped slider", "stack", "studio",
        `.box{max-width:420px;padding:32px 20px}input{width:100%;accent-color:var(--accent)}`,
        `<label class="box fld">Rooms <span id="n">2</span><input type="range" min="1" max="6" value="2" step="1" oninput="document.getElementById('n').textContent=this.value"></label>`),
      v("dual-slider", "Min and max sliders", "stack", "soft",
        `.box{max-width:440px;padding:24px 20px;display:grid;gap:16px}input{width:100%;accent-color:var(--accent)}`,
        `<div class="box"><label class="fld">Minimum <span id="a">4</span> weeks<input type="range" min="1" max="12" value="4" oninput="document.getElementById('a').textContent=this.value"></label><label class="fld">Maximum <span id="c">8</span> weeks<input type="range" min="1" max="16" value="8" oninput="document.getElementById('c').textContent=this.value"></label></div>`),
      v("vertical-slider", "Vertical slider", "stack", "sharp",
        `.box{padding:24px;display:flex;align-items:center;gap:16px}input{writing-mode:vertical-lr;direction:rtl;height:180px;width:28px;accent-color:var(--accent)}`,
        `<label class="box">Volume<input type="range" min="0" max="100" value="40" aria-valuetext="40 percent" oninput="this.setAttribute('aria-valuetext', this.value+' percent')"></label>`),
    ]),
    atom("search", ["form-fields"], [
      v("search-field", "Search field", "form-stack", "editorial",
        `.box{max-width:480px;padding:28px 20px}`,
        `<form class="box" role="search"><label class="fld">Search<input type="search" name="q" placeholder="Projects, materials, notes"></label></form>`),
      v("search-button", "Search with button", "flex-row", "studio",
        `form{display:flex;gap:8px;max-width:520px;padding:24px 20px}input{flex:1}`,
        `<form role="search"><label class="fld" style="flex:1">Search<input type="search" name="q"></label><button class="btn" type="submit">Search</button></form>`),
      v("search-results", "Search with results", "stack", "soft",
        `.box{max-width:480px;padding:20px}li{list-style:none;padding:10px 0;border-bottom:1px solid var(--line)}ul{margin:8px 0 0;padding:0}`,
        `<div class="box"><label class="fld">Find<input type="search" value="oak"></label><ul><li>White oak stair</li><li>Oak supply visit</li></ul></div>`),
      v("expand-search", "Quiet search", "stack", "sharp",
        `input{width:min(360px,calc(100% - 40px));margin:28px 20px;border:0;border-bottom:1px solid var(--line);border-radius:0;background:transparent}`,
        `<label class="fld" style="padding:8px 20px">Search the archive<input type="search" placeholder="Type a room"></label>`),
    ]),
    atom("uploads", ["form-fields"], [
      v("drop-upload", "Dropzone upload", "stack", "editorial",
        `.drop{max-width:460px;margin:24px;padding:28px;border:1px dashed var(--line);border-radius:var(--r);text-align:center;position:relative;background:var(--surface)}input{position:absolute;inset:0;opacity:0;cursor:pointer}`,
        `<label class="drop"><strong>Drop plans</strong><p class="lede">PDF or images, up to 20 MB.</p><input type="file" accept="image/*,.pdf"></label>`),
      v("button-upload", "Button upload", "flex-row", "studio",
        `label.btn{position:relative;overflow:hidden;margin:24px}input{position:absolute;inset:0;opacity:0}`,
        `<label class="btn">Choose a file<input type="file"></label>`),
      v("list-upload", "Upload list", "stack", "soft",
        `.file{display:flex;justify-content:space-between;gap:12px;align-items:center;max-width:460px;margin:8px 20px;padding:10px 12px;background:var(--surface);border-radius:var(--r)}`,
        `<div><div class="file"><span>plan-a.pdf</span><span class="lede">2.1 MB</span></div><div class="file"><span>stair.jpg</span><span class="lede">Ready</span></div></div>`),
      v("image-upload", "Image upload", "card-grid", "sharp",
        `.tile{width:160px;height:160px;margin:24px;border:1px dashed var(--line);display:grid;place-items:center;position:relative}input{position:absolute;inset:0;opacity:0}`,
        `<label class="tile">Add photo<input type="file" accept="image/*"></label>`),
    ]),
    atom("date-pickers", ["form-fields"], [
      v("native-date", "Native date", "form-stack", "editorial",
        `.box{max-width:320px;padding:24px 20px}`,
        `<div class="box"><label class="fld">Visit date<input type="date"></label><label class="fld">Time<input type="time"></label></div>`),
      v("calendar-grid", "Calendar grid", "card-grid", "studio",
        `.cal{max-width:320px;margin:20px;background:var(--surface);padding:12px;border-radius:var(--r);border:1px solid var(--line)}.days{display:grid;grid-template-columns:repeat(7,1fr);gap:4px}button{min-height:40px;border:0;background:transparent;border-radius:8px}button[aria-pressed=true]{background:var(--accent);color:var(--on)}`,
        `<div class="cal"><p class="ey">March</p><div class="days" role="group" aria-label="March">${Array.from({length:28},(_,i)=>`<button type="button" aria-pressed="${i===11?"true":"false"}">${i+1}</button>`).join("")}</div></div>`),
      v("range-date", "Date range", "form-stack", "soft",
        `.box{display:grid;grid-template-columns:1fr 1fr;gap:10px;max-width:460px;padding:24px 20px}`,
        `<div class="box"><label class="fld">From<input type="date"></label><label class="fld">To<input type="date"></label></div>`),
      v("inline-date", "Inline date field", "stack", "sharp",
        `.row{display:flex;gap:8px;align-items:end;padding:24px 20px;max-width:420px}`,
        `<div class="row"><label class="fld">Day<input type="date"></label><button class="btn" type="button">Apply</button></div>`),
    ]),
    atom("color-pickers", ["form-fields"], [
      v("swatch-color", "Swatches", "flex-row", "editorial",
        `.row{display:flex;gap:8px;padding:24px;flex-wrap:wrap}label{width:48px;height:48px;border-radius:50%;border:1px solid var(--line);display:grid;place-items:center}input{opacity:0;position:absolute}span{width:28px;height:28px;border-radius:50%;display:block}`,
        `<div class="row" role="radiogroup" aria-label="Finish">${[["#1b1814","Ink"],["#6e3824","Clay"],["#d8d2c8","Stone"],["#f3efe7","Paper"]].map(([c,n],i)=>`<label style="position:relative" title="${n}"><input type="radio" name="c" ${i===0?"checked":""} aria-label="${n}"><span style="background:${c}"></span></label>`).join("")}</div>`),
      v("field-color", "Color field", "form-stack", "studio",
        `.box{display:flex;gap:12px;align-items:center;padding:24px}input[type=color]{width:48px;height:48px;border:1px solid var(--line);background:transparent;padding:0}`,
        `<label class="box">Accent<input type="color" value="#f5f6f8" aria-label="Accent color"></label>`),
      v("palette-color", "Palette list", "stack", "soft",
        `.row{display:flex;justify-content:space-between;align-items:center;max-width:360px;padding:10px 20px;border-bottom:1px solid var(--line)}.chip{width:28px;height:28px;border-radius:50%;border:1px solid var(--line)}`,
        `<div><div class="row"><span>Ink</span><span class="chip" style="background:#1b1814"></span></div><div class="row"><span>Clay</span><span class="chip" style="background:#6e3824"></span></div><div class="row"><span>Paper</span><span class="chip" style="background:#f3efe7"></span></div></div>`),
      v("custom-color", "Hex color", "form-stack", "sharp",
        `.box{display:flex;gap:8px;padding:24px;max-width:360px}input[type=color]{width:48px;height:48px;padding:0;border:1px solid var(--line)}`,
        `<div class="box"><input type="color" value="#111111" aria-label="Pick color"><label class="fld" style="flex:1">Hex<input value="#111111"></label></div>`),
    ]),
  ];
};
