"use strict";

module.exports = function overlays({ I, JS }) {
  const v = (slug, title, layout, family, css, html, js = "") => ({ slug, title, layout, family, css, html, js });
  const atom = (category, slots, variants) => ({ category, role: "ornament", pageReady: false, slots, variants });

  return [
    atom("modals", ["headline", "cta"], [
      v("center-modal", "Center dialog", "centered", "editorial",
        `dialog{border:1px solid var(--line);border-radius:var(--r);background:var(--surface);color:var(--ink);padding:22px;max-width:min(440px,calc(100% - 24px));box-shadow:var(--sh)}dialog::backdrop{background:rgba(0,0,0,.45)}.pad{padding:32px}`,
        `<div class="pad"><button class="btn" type="button" data-open="d1">Open dialog</button></div><dialog id="d1" aria-labelledby="t1"><h2 id="t1">Save this plan?</h2><p class="lede">You can return to it from the project list.</p><div style="display:flex;gap:8px;margin-top:16px"><button class="btn" type="button" data-close>Save</button><button class="btn gh" type="button" data-close>Cancel</button></div></dialog>`,
        JS.modal),
      v("sheet-modal", "Bottom sheet", "band", "studio",
        `dialog{border:0;border-top:1px solid var(--line);width:100%;max-width:100%;margin-top:auto;background:var(--surface);color:inherit;padding:20px;border-radius:var(--r) var(--r) 0 0}dialog::backdrop{background:rgba(0,0,0,.5)}.pad{padding:24px}`,
        `<div class="pad"><button class="btn" type="button" data-open="s1">Open sheet</button></div><dialog id="s1"><h2>Share</h2><p class="lede">Copy a link for the client.</p><button class="btn" type="button" data-close style="margin-top:12px">Done</button></dialog>`,
        JS.modal),
      v("confirm-modal", "Confirm dialog", "centered", "soft",
        `dialog{border:1px solid var(--line);border-radius:var(--r);padding:20px;background:var(--surface);color:inherit}dialog::backdrop{background:rgba(42,30,24,.4)}.pad{padding:28px}`,
        `<div class="pad"><button class="btn" type="button" data-open="c1">Remove sample</button></div><dialog id="c1"><h2>Remove this sample?</h2><p class="lede">The finish stays in the library.</p><div style="display:flex;gap:8px;margin-top:14px"><button class="btn" type="button" data-close>Remove</button><button class="btn gh" type="button" data-close>Keep</button></div></dialog>`,
        JS.modal),
      v("media-modal", "Media dialog", "split-media", "sharp",
        `dialog{padding:0;border:1px solid var(--line);background:var(--surface);max-width:min(640px,calc(100% - 24px))}dialog img{width:100%}dialog div{padding:14px 16px 16px}dialog::backdrop{background:rgba(0,0,0,.55)}.pad{padding:24px}`,
        `<div class="pad"><button class="btn" type="button" data-open="m1">View photo</button></div><dialog id="m1"><img src="https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=1200&q=80" alt="Living room"><div><h2>Hill house</h2><button class="btn gh" type="button" data-close>Close</button></div></dialog>`,
        JS.modal),
    ]),
    atom("dropdowns", ["nav-links"], [
      v("menu-dropdown", "Menu dropdown", "stack", "editorial",
        `.box{padding:28px;position:relative;display:inline-block}ul{position:absolute;margin:6px 0 0;padding:6px;list-style:none;background:var(--surface);border:1px solid var(--line);border-radius:var(--r);min-width:200px;box-shadow:var(--sh)}a,button{display:flex;width:100%;min-height:44px;align-items:center;padding:0 10px;background:none;border:0;text-align:left}`,
        `<div class="box" data-drop><button class="btn gh" type="button" aria-expanded="false" aria-haspopup="menu">Work ${I.chev}</button><ul data-menu hidden role="menu"><li><a href="#homes" role="menuitem">Homes</a></li><li><a href="#shops" role="menuitem">Shops</a></li></ul></div>`,
        JS.drop),
      v("icon-dropdown", "Icon dropdown", "stack", "studio",
        `.box{padding:24px}ul{list-style:none;margin:8px 0 0;padding:6px;border:1px solid var(--line);border-radius:var(--r);background:var(--surface);width:220px}button.item{width:100%;text-align:left;background:none;border:0;min-height:44px;color:inherit}`,
        `<div class="box" data-drop><button class="btn" type="button" aria-label="More actions" aria-expanded="false">${I.menu}</button><ul data-menu hidden><li><button class="item" type="button">Duplicate</button></li><li><button class="item" type="button">Archive</button></li></ul></div>`,
        JS.drop),
      v("split-dropdown", "Split button dropdown", "flex-row", "soft",
        `.grp{display:inline-flex;margin:24px}.grp .btn:first-child{border-radius:var(--r) 0 0 var(--r)}.grp .btn:last-child{border-radius:0 var(--r) var(--r) 0;padding:0 12px}`,
        `<div class="grp"><button class="btn" type="button">Publish</button><button class="btn" type="button" aria-label="More publish options">${I.chev}</button></div>`),
      v("nested-dropdown", "Described menu", "stack", "sharp",
        `.box{padding:20px;max-width:280px}a{display:block;padding:10px 0;border-bottom:1px solid var(--line)}`,
        `<nav class="box" aria-label="Studio"><a href="#visit"><strong>Book</strong><span class="lede" style="display:block">Choose a Thursday.</span></a><a href="#work"><strong>Work</strong><span class="lede" style="display:block">Recent rooms.</span></a></nav>`),
    ]),
    atom("menus", ["nav-links"], [
      v("horizontal-menu", "Horizontal menu", "nav-bar", "editorial",
        `nav{display:flex;gap:18px;padding:20px}.a{min-height:44px;display:inline-flex;align-items:center}[aria-current]{border-bottom:2px solid var(--ink)}`,
        `<nav aria-label="Section"><a class="a" href="#one" aria-current="page">Overview</a><a class="a" href="#two">Notes</a><a class="a" href="#three">Files</a></nav>`),
      v("context-menu", "Context menu", "stack", "studio",
        `ul{list-style:none;margin:24px;padding:6px;width:200px;background:var(--surface);border:1px solid var(--line);border-radius:var(--r)}button{width:100%;text-align:left;background:none;border:0;min-height:44px;color:inherit;padding:0 10px}`,
        `<ul role="menu" aria-label="Item actions"><li><button type="button" role="menuitem">Rename</button></li><li><button type="button" role="menuitem">Move</button></li><li><button type="button" role="menuitem">Delete</button></li></ul>`),
      v("hamburger-menu", "Hamburger panel", "nav-bar", "soft",
        `.top{display:flex;justify-content:space-between;align-items:center;padding:8px 12px}button{width:48px;height:48px;border:0;background:transparent}nav a{display:flex;min-height:48px;align-items:center;padding:0 16px}`,
        `<header data-nav><div class="top"><span class="brand">Northline</span><button type="button" data-burger aria-expanded="false" aria-label="Open menu">${I.menu}</button></div><nav id="m" hidden><a href="#work">Work</a><a href="#visit">Visit</a></nav></header><script>document.querySelector("[data-burger]").onclick=function(){const n=document.getElementById("m");n.hidden=!n.hidden;this.setAttribute("aria-expanded",String(!n.hidden));}</script>`),
      v("vertical-menu", "Vertical menu", "stack", "sharp",
        `nav{display:grid;max-width:220px;padding:12px}a{min-height:44px;display:flex;align-items:center;padding:0 8px}[aria-current]{background:var(--surface);font-weight:700}`,
        `<nav aria-label="Settings"><a href="#a" aria-current="page">Account</a><a href="#b">Billing</a><a href="#c">Notifications</a></nav>`),
    ]),
    atom("tabs", ["section-header"], [
      v("underline-tabs", "Underline tabs", "flex-row", "editorial",
        `[role=tablist]{display:flex;gap:8px;border-bottom:1px solid var(--line)}[role=tab]{min-height:48px;padding:0 12px;border:0;background:none;border-bottom:2px solid transparent;color:inherit}[aria-selected=true]{border-color:var(--ink);font-weight:700}.panel{padding:16px 4px}`,
        `<div data-tabs class="w" style="padding-top:20px"><div role="tablist" aria-label="Project"><button role="tab" aria-selected="true" id="t1" aria-controls="p1">Brief</button><button role="tab" aria-selected="false" id="t2" aria-controls="p2" tabindex="-1">Files</button></div><div role="tabpanel" id="p1" aria-labelledby="t1" class="panel">The kitchen faces west. Keep the afternoon shade.</div><div role="tabpanel" id="p2" aria-labelledby="t2" class="panel" hidden>Two PDFs and a photo set.</div></div>`,
        JS.tabs),
      v("boxed-tabs", "Boxed tabs", "card-grid", "studio",
        `[role=tablist]{display:flex;gap:6px}[role=tab]{min-height:44px;padding:0 12px;border:1px solid var(--line);background:transparent;color:inherit;border-radius:var(--r)}[aria-selected=true]{background:var(--accent);color:var(--on)}.panel{padding:16px 0}`,
        `<div data-tabs style="padding:20px"><div role="tablist"><button role="tab" aria-selected="true" id="a" aria-controls="pa">Active</button><button role="tab" aria-selected="false" id="b" aria-controls="pb" tabindex="-1">Archive</button></div><div role="tabpanel" id="pa" class="panel">Three open rooms.</div><div role="tabpanel" id="pb" class="panel" hidden>Last season’s shops.</div></div>`,
        JS.tabs),
      v("vertical-tabs", "Vertical tabs", "split-media", "soft",
        `.vt{display:grid;grid-template-columns:180px 1fr;min-height:220px}[role=tab]{display:flex;width:100%;text-align:left;min-height:48px;border:0;background:none;color:inherit;padding:0 12px}[aria-selected=true]{background:var(--surface);font-weight:700}@media(max-width:800px){.vt{grid-template-columns:1fr}}`,
        `<div class="vt" data-tabs><div role="tablist" aria-orientation="vertical"><button role="tab" aria-selected="true" id="v1" aria-controls="vp1">Profile</button><button role="tab" aria-selected="false" id="v2" aria-controls="vp2" tabindex="-1">Access</button></div><div role="tabpanel" id="vp1" style="padding:16px">Name, role, and photo.</div><div role="tabpanel" id="vp2" hidden style="padding:16px">Who can edit the drawings.</div></div>`,
        JS.tabs),
      v("segment-tabs", "Segment tabs", "flex-row", "sharp",
        `[role=tablist]{display:inline-flex;border:1px solid var(--line);margin:20px}[role=tab]{border:0;background:transparent;min-height:44px;padding:0 14px;color:inherit}[aria-selected=true]{background:var(--ink);color:var(--on)}`,
        `<div data-tabs><div role="tablist" aria-label="Density"><button role="tab" aria-selected="true" id="s1" aria-controls="sp1">Comfortable</button><button role="tab" aria-selected="false" id="s2" aria-controls="sp2" tabindex="-1">Compact</button></div><p id="sp1" role="tabpanel">More air between rows.</p><p id="sp2" role="tabpanel" hidden>Tighter tables.</p></div>`,
        JS.tabs),
    ]),
    atom("tooltips", ["visual"], [
      v("hover-tooltip", "Focus tooltip", "stack", "editorial",
        `.tip{position:relative;display:inline-block;margin:48px}.bubble{position:absolute;left:0;top:calc(100% + 8px);background:var(--ink);color:var(--on);padding:8px 10px;border-radius:8px;width:max-content;max-width:220px}`,
        `<span class="tip"><button class="btn gh" type="button" aria-describedby="tip1">Lead time</button><span role="tooltip" id="tip1" class="bubble">Design books about three weeks out.</span></span>`),
      v("rich-tooltip", "Rich tooltip", "card-grid", "studio",
        `.card{max-width:260px;margin:24px;padding:14px;background:var(--surface);border:1px solid var(--line);border-radius:var(--r)}`,
        `<aside class="card" role="note"><strong>Sample library</strong><p class="lede">Open Saturday until 2. Ask for the oak set.</p></aside>`),
      v("icon-tooltip", "Icon with label", "flex-row", "soft",
        `.row{display:flex;gap:8px;align-items:center;padding:28px}`,
        `<p class="row"><button class="btn gh" type="button" aria-label="More about deposits" style="width:48px;padding:0">${I.info}</button><span>Half is due to begin drawings.</span></p>`),
      v("inline-tooltip", "Inline definition", "stack", "sharp",
        `dfn{font-style:normal;border-bottom:1px dashed var(--muted);cursor:help}.note{max-width:420px;padding:24px}`,
        `<p class="note">We specify <dfn title="A matte mineral paint that can be patched.">limewash</dfn> on plaster, not on new drywall.</p>`),
    ]),
    atom("popovers", ["visual"], [
      v("menu-popover", "Menu popover", "stack", "editorial",
        `.box{padding:24px;position:relative;display:inline-block}[data-menu]{position:absolute;background:var(--surface);border:1px solid var(--line);border-radius:var(--r);padding:8px;width:220px;box-shadow:var(--sh)}`,
        `<div class="box" data-drop><button class="btn gh" type="button" aria-expanded="true">Filters</button><div data-menu><label class="fld">City<input value="Harbor"></label></div></div>`,
        JS.drop),
      v("info-popover", "Info popover", "card-grid", "studio",
        `.card{max-width:280px;margin:20px;padding:14px;border-radius:var(--r);background:var(--surface);border:1px solid var(--line)}`,
        `<div class="card"><strong>Allowance</strong><p class="lede">A number we publish before demo, not after.</p></div>`),
      v("form-popover", "Form popover", "form-stack", "soft",
        `form{max-width:280px;margin:20px;padding:14px;background:var(--surface);border-radius:var(--r);display:grid;gap:8px;border:1px solid var(--line)}`,
        `<form><label class="fld">Rename<input value="Hill house"></label><button class="btn" type="button">Save</button></form>`),
      v("anchor-popover", "Anchored note", "stack", "sharp",
        `.row{padding:24px}.note{margin-top:8px;padding:10px 12px;border:1px solid var(--line);max-width:280px}`,
        `<div class="row"><button class="btn gh" type="button" aria-describedby="n1">Why Thursday?</button><p class="note" id="n1" role="note">The light is honest, and the studio is staffed.</p></div>`),
    ]),
    atom("toasts", ["visual"], [
      v("success-toast", "Success toast", "band", "editorial",
        `.toast{position:fixed;right:16px;bottom:16px;background:var(--ink);color:var(--on);padding:12px 14px;border-radius:var(--r);display:flex;gap:10px;align-items:center;max-width:min(360px,calc(100% - 32px))}.pad{padding:24px}`,
        `<div class="pad"><button class="btn" type="button" data-toast-btn>Save note</button></div><div class="toast" data-toast hidden role="status">${I.check} Saved to the project.</div>`,
        JS.toast),
      v("action-toast", "Toast with action", "band", "studio",
        `.toast{margin:20px;display:flex;justify-content:space-between;gap:12px;align-items:center;padding:12px 14px;background:var(--surface);border:1px solid var(--line);border-radius:var(--r);max-width:420px}`,
        `<div class="toast" role="status"><span>Sample archived.</span><button class="btn gh" type="button">Undo</button></div>`),
      v("error-toast", "Error toast", "band", "soft",
        `.toast{margin:20px;padding:12px 14px;border-radius:var(--r);background:#f8ece8;color:#5c2418;max-width:420px;display:flex;gap:8px}`,
        `<div class="toast" role="alert">${I.alert} The file is larger than 20 MB.</div>`),
      v("stack-toast", "Stacked toasts", "stack", "sharp",
        `.stack{display:grid;gap:8px;padding:16px;max-width:360px}.t{border:1px solid var(--line);padding:10px 12px;background:var(--surface)}`,
        `<div class="stack" aria-live="polite"><div class="t" role="status">Drawing uploaded.</div><div class="t" role="status">Client notified.</div></div>`),
    ]),
    atom("notifications", ["visual"], [
      v("banner-note", "Banner notification", "band", "editorial",
        `.bar{display:flex;justify-content:space-between;gap:12px;align-items:center;padding:12px 16px;background:var(--surface);border-bottom:1px solid var(--line)}`,
        `<div class="bar" role="status"><span>Two drawings need a review.</span><a class="btn" href="#files">Review</a></div>`),
      v("inbox-note", "Inbox row", "stack", "studio",
        `article{display:grid;grid-template-columns:1fr auto;gap:8px;padding:14px 16px;border-bottom:1px solid var(--line)}`,
        `<article><div><strong>Ada mentioned you</strong><p class="lede">On the stair drawing.</p></div><time class="lede">2h</time></article>`),
      v("stacked-notes", "Stacked notifications", "stack", "soft",
        `article{margin:10px 16px;padding:12px;background:var(--surface);border-radius:var(--r);border:1px solid var(--line)}`,
        `<div><article><strong>Visit confirmed</strong><p class="lede">Thursday, 10:00.</p></article><article><strong>Sample shipped</strong><p class="lede">Oak set, two days.</p></article></div>`),
      v("dot-note", "Unread notification", "flex-row", "sharp",
        `.row{display:flex;gap:10px;align-items:center;padding:16px}.dot{width:8px;height:8px;border-radius:50%;background:var(--ink)}`,
        `<p class="row"><span class="dot" aria-hidden="true"></span> Unread note from the crew</p>`),
    ]),
    atom("alerts", ["visual"], [
      v("info-alert", "Info alert", "band", "editorial",
        `.a{display:flex;gap:10px;margin:16px;padding:12px 14px;border:1px solid var(--line);border-radius:var(--r);background:var(--surface);max-width:520px}`,
        `<div class="a" role="status">${I.info}<div><strong>Info.</strong> The library is open Saturday.</div></div>`),
      v("success-alert", "Success alert", "band", "studio",
        `.a{display:flex;gap:10px;margin:16px;padding:12px 14px;border-radius:var(--r);background:#e7f4ec;color:#143324;max-width:520px}`,
        `<div class="a" role="status">${I.check}<div><strong>Sent.</strong> The client has the link.</div></div>`),
      v("warning-alert", "Warning alert", "band", "soft",
        `.a{display:flex;gap:10px;margin:16px;padding:12px 14px;border-radius:var(--r);background:#f8f1e4;color:#4a3412;max-width:520px}`,
        `<div class="a" role="status">${I.alert}<div><strong>Warning.</strong> This finish stains. Confirm before order.</div></div>`),
      v("danger-alert", "Danger alert", "band", "sharp",
        `.a{display:flex;gap:10px;margin:16px;padding:12px 14px;border:1px solid #e7c8c4;border-radius:var(--r);background:#f8ecec;color:#5c2418;max-width:520px}`,
        `<div class="a" role="alert">${I.alert}<div><strong>Error.</strong> The upload failed. Try a smaller PDF.</div></div>`),
    ]),
    atom("drawers", ["nav-links"], [
      v("left-drawer", "Left drawer", "stack", "editorial",
        `aside{width:min(320px,100%);min-height:100vh;background:var(--surface);border-right:1px solid var(--line);padding:18px}a{display:flex;min-height:44px;align-items:center}`,
        `<aside aria-label="Menu"><p class="brand">Northline</p><a href="#work">Work</a><a href="#visit">Visit</a><button class="btn gh" type="button" style="margin-top:12px">Close</button></aside>`),
      v("right-drawer", "Right drawer", "stack", "studio",
        `aside{margin-left:auto;width:min(340px,100%);min-height:100vh;background:var(--surface);border-left:1px solid var(--line);padding:18px}`,
        `<aside aria-label="Details"><h2>Hill house</h2><p class="lede">Kitchen and stair. Due in June.</p><button class="btn" type="button" style="margin-top:12px">Open project</button></aside>`),
      v("bottom-drawer", "Bottom drawer", "band", "soft",
        `aside{position:sticky;bottom:0;background:var(--surface);border-top:1px solid var(--line);padding:16px;display:flex;justify-content:space-between;gap:12px;align-items:center}`,
        `<div style="min-height:40vh"></div><aside><div><strong>Ready to book?</strong><p class="lede">Thursday mornings.</p></div><a class="btn" href="#visit">Book</a></aside>`),
      v("nav-drawer", "Navigation drawer", "nav-bar", "sharp",
        `aside{width:240px;min-height:100vh;border-right:1px solid var(--line);padding:12px}a{display:flex;min-height:44px;align-items:center;padding:0 8px}[aria-current]{font-weight:750}`,
        `<aside aria-label="App"><a href="#in" aria-current="page">Inbox</a><a href="#pr">Projects</a><a href="#se">Settings</a></aside>`),
    ]),
    atom("command", ["form-fields"], [
      v("command-palette", "Command palette", "stack", "editorial",
        `.box{max-width:480px;margin:24px auto;background:var(--surface);border:1px solid var(--line);border-radius:var(--r);box-shadow:var(--sh);overflow:hidden}input{width:100%;border:0;border-bottom:1px solid var(--line);min-height:52px;padding:0 14px;background:transparent}button{width:100%;text-align:left;background:none;border:0;min-height:44px;padding:0 14px;color:inherit}`,
        `<div class="box" role="dialog" aria-label="Commands"><input data-cmd type="search" placeholder="Jump to…" aria-label="Command search"><button type="button" data-cmd-item>Go to projects</button><button type="button" data-cmd-item>New note</button><button type="button" data-cmd-item>Book a visit</button></div>`,
        JS.cmd),
      v("grouped-command", "Grouped commands", "stack", "studio",
        `.box{max-width:420px;margin:20px;background:var(--surface);border-radius:var(--r);padding:8px 0;border:1px solid var(--line)}p{padding:8px 12px}button{display:block;width:100%;text-align:left;background:none;border:0;color:inherit;min-height:40px;padding:0 12px}`,
        `<div class="box"><p class="ey">Navigate</p><button type="button">Work</button><button type="button">Journal</button><p class="ey">Create</p><button type="button">Project</button></div>`),
      v("empty-command", "Empty command search", "stack", "soft",
        `.box{max-width:420px;margin:20px;padding:16px;border:1px solid var(--line);border-radius:var(--r);background:var(--surface)}`,
        `<div class="box"><label class="fld">Search<input value="zzz" aria-label="Commands"></label><p class="lede" style="margin-top:10px">No matching commands.</p></div>`),
      v("filtered-command", "Filtered commands", "stack", "sharp",
        `.box{max-width:420px;margin:20px;border:1px solid var(--line)}input{width:100%;border:0;border-bottom:1px solid var(--line);padding:12px}li{list-style:none;padding:10px 12px;border-bottom:1px solid var(--line)}ul{margin:0;padding:0}`,
        `<div class="box"><input value="book" aria-label="Filter"><ul><li>Book a visit</li><li>Booking rules</li></ul></div>`),
    ]),
    atom("cookie", ["cta"], [
      v("bar-cookie", "Consent bar", "band", "editorial",
        `.bar{position:sticky;bottom:0;display:flex;justify-content:space-between;gap:12px;flex-wrap:wrap;align-items:center;padding:14px 16px;background:var(--surface);border-top:1px solid var(--line)}`,
        `<aside class="bar" role="dialog" aria-label="Cookie consent"><p>We use necessary cookies and optional analytics.</p><div style="display:flex;gap:8px"><button class="btn gh" type="button">Reject</button><button class="btn" type="button">Accept</button></div></aside>`),
      v("corner-cookie", "Corner consent", "card-grid", "studio",
        `.card{max-width:320px;margin:20px;padding:16px;background:var(--surface);border-radius:var(--r);border:1px solid var(--line)}`,
        `<aside class="card" role="dialog" aria-label="Privacy"><h2 style="font-size:1.3rem">Cookies</h2><p class="lede">Analytics stays off unless you allow it.</p><div style="display:flex;gap:8px;margin-top:12px"><button class="btn gh" type="button">No</button><button class="btn" type="button">Allow</button></div></aside>`),
      v("prefs-cookie", "Consent preferences", "stack", "soft",
        `.card{max-width:420px;margin:16px;padding:16px;background:var(--surface);border-radius:var(--r)}label{display:flex;justify-content:space-between;gap:12px;min-height:44px;align-items:center}`,
        `<form class="card"><h2 style="font-size:1.4rem">Preferences</h2><label>Necessary <input type="checkbox" checked disabled></label><label>Analytics <input type="checkbox"></label><button class="btn" type="button">Save</button></form>`),
      v("modal-cookie", "Consent dialog", "centered", "sharp",
        `.card{max-width:440px;margin:20px;padding:18px;border:1px solid var(--line);background:var(--surface)}`,
        `<aside class="card" role="dialog" aria-labelledby="ck"><h2 id="ck">Before you continue</h2><p class="lede">Choose whether we measure visits.</p><div style="display:flex;gap:8px;margin-top:12px"><button class="btn gh" type="button">Essential only</button><button class="btn" type="button">Accept all</button></div></aside>`),
    ]),
    atom("sidebars", ["nav-links"], [
      v("collapsible-sidebar", "Labeled sidebar", "stack", "editorial",
        `aside{width:240px;min-height:100vh;border-right:1px solid var(--line);padding:16px;background:var(--surface)}a{display:flex;min-height:44px;align-items:center;gap:8px}`,
        `<aside aria-label="Projects"><p class="ey">Studio</p><a href="#a" aria-current="page">All work</a><a href="#b">Active</a><a href="#c">Archive</a></aside>`),
      v("icon-rail", "Icon rail", "stack", "studio",
        `aside{width:72px;min-height:100vh;border-right:1px solid var(--line);display:grid;align-content:start;justify-items:center;gap:6px;padding:10px 0}a{width:48px;height:48px;display:grid;place-items:center;border-radius:12px}[aria-current]{background:var(--surface)}`,
        `<aside aria-label="Primary"><a href="#h" aria-label="Home" aria-current="page">${I.pin}</a><a href="#s" aria-label="Search">${I.search}</a><a href="#u" aria-label="Account">${I.user}</a></aside>`),
      v("overlay-sidebar", "Overlay sidebar", "stack", "soft",
        `aside{width:min(300px,100%);min-height:100vh;background:var(--surface);padding:16px;box-shadow:var(--sh)}`,
        `<aside aria-label="Menu"><button class="btn gh" type="button" aria-label="Close menu">${I.close}</button><a class="brand" href="#top" style="display:block;margin:12px 0">Northline</a><a href="#work" style="display:flex;min-height:44px;align-items:center">Work</a></aside>`),
      v("dual-sidebar", "Dual sidebar", "split-media", "sharp",
        `.app{display:grid;grid-template-columns:200px 1fr 220px;min-height:100vh}aside{border-right:1px solid var(--line);padding:12px}aside:last-child{border-right:0;border-left:1px solid var(--line)}@media(max-width:800px){.app{grid-template-columns:1fr}aside:last-child{display:none}}`,
        `<div class="app"><aside aria-label="Sections"><a href="#w">Work</a></aside><main style="padding:16px"><h2>Board</h2></main><aside aria-label="Details"><p class="lede">Select a project.</p></aside></div>`),
    ]),
    atom("docks", ["nav-links", "cta"], [
      v("bottom-dock", "Bottom dock", "nav-bar", "editorial",
        `nav{position:sticky;bottom:0;display:flex;justify-content:space-around;background:var(--surface);border-top:1px solid var(--line);padding:6px}a{min-width:64px;min-height:48px;display:flex;flex-direction:column;align-items:center;justify-content:center;font-size:.75rem;gap:2px}`,
        `<div style="min-height:50vh"></div><nav aria-label="Mobile"><a href="#h" aria-current="page">${I.pin}<span>Home</span></a><a href="#s">${I.search}<span>Search</span></a><a href="#v">${I.mail}<span>Visit</span></a><a href="#u">${I.user}<span>You</span></a></nav>`),
      v("floating-dock", "Floating dock", "centered", "studio",
        `nav{width:min(420px,calc(100% - 24px));margin:24px auto;display:flex;justify-content:space-around;padding:8px;border-radius:var(--r);background:color-mix(in srgb,var(--surface) 88%,transparent);border:1px solid var(--line);box-shadow:var(--sh)}a{min-width:48px;min-height:48px;display:grid;place-items:center}`,
        `<nav aria-label="Shortcuts"><a href="#h" aria-label="Home">${I.pin}</a><a href="#w" aria-label="Work">${I.star}</a><a href="#v" aria-label="Visit">${I.mail}</a></nav>`),
      v("vertical-dock", "Vertical dock", "stack", "soft",
        `nav{display:grid;gap:6px;width:72px;padding:10px;min-height:100vh;border-right:1px solid var(--line)}a{height:48px;display:grid;place-items:center}`,
        `<nav aria-label="Tools"><a href="#a" aria-label="Projects">${I.pin}</a><a href="#b" aria-label="People">${I.user}</a><a href="#c" aria-label="Settings">${I.info}</a></nav>`),
      v("mac-dock", "Icon dock with labels", "flex-row", "sharp",
        `nav{display:flex;gap:8px;padding:16px}a{min-height:48px;display:flex;align-items:center;gap:6px;padding:0 10px;border:1px solid var(--line)}`,
        `<nav aria-label="Dock"><a href="#w">${I.star} Work</a><a href="#n">${I.mail} Notes</a><a href="#c">${I.clock} Hours</a></nav>`),
    ]),
  ];
};
